// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateData, CreateErrors, CreateResponses, DeleteData, DeleteErrors, DeleteResponses, GetAllData, GetAllErrors, GetAllResponses, GetPromptByIdOrAliasData, GetPromptByIdOrAliasErrors, GetPromptByIdOrAliasResponses, UpdateData, UpdateErrors, UpdateResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class PromptsService {
    public static getAll<ThrowOnError extends boolean = false>(options?: Options<GetAllData, ThrowOnError>) {
        return (options?.client ?? client).get<GetAllResponses, GetAllErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/prompts',
            ...options
        });
    }
    
    public static create<ThrowOnError extends boolean = false>(options?: Options<CreateData, ThrowOnError>) {
        return (options?.client ?? client).post<CreateResponses, CreateErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/prompts',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static delete<ThrowOnError extends boolean = false>(options: Options<DeleteData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteResponses, DeleteErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/prompts/{promptIdOrAlias}',
            ...options
        });
    }
    
    public static getPromptByIdOrAlias<ThrowOnError extends boolean = false>(options: Options<GetPromptByIdOrAliasData, ThrowOnError>) {
        return (options.client ?? client).get<GetPromptByIdOrAliasResponses, GetPromptByIdOrAliasErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/prompts/{promptIdOrAlias}',
            ...options
        });
    }
    
    public static update<ThrowOnError extends boolean = false>(options: Options<UpdateData, ThrowOnError>) {
        return (options.client ?? client).put<UpdateResponses, UpdateErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/prompts/{promptIdOrAlias}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class UmbracoAiPromptService {
    public static getAll<ThrowOnError extends boolean = false>(options?: Options<GetAllData, ThrowOnError>) {
        return (options?.client ?? client).get<GetAllResponses, GetAllErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/prompts',
            ...options
        });
    }
    
    public static create<ThrowOnError extends boolean = false>(options?: Options<CreateData, ThrowOnError>) {
        return (options?.client ?? client).post<CreateResponses, CreateErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/prompts',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static delete<ThrowOnError extends boolean = false>(options: Options<DeleteData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteResponses, DeleteErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/prompts/{promptIdOrAlias}',
            ...options
        });
    }
    
    public static getPromptByIdOrAlias<ThrowOnError extends boolean = false>(options: Options<GetPromptByIdOrAliasData, ThrowOnError>) {
        return (options.client ?? client).get<GetPromptByIdOrAliasResponses, GetPromptByIdOrAliasErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/prompts/{promptIdOrAlias}',
            ...options
        });
    }
    
    public static update<ThrowOnError extends boolean = false>(options: Options<UpdateData, ThrowOnError>) {
        return (options.client ?? client).put<UpdateResponses, UpdateErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/prompts/{promptIdOrAlias}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
