using System.Text.Json;
using Umbraco.Ai.Core.Tests;
using Umbraco.Ai.Web.Api.Management.Test.Models;
using Umbraco.Cms.Core.Mapping;

namespace Umbraco.Ai.Web.Api.Management.Test.Mapping;

/// <summary>
/// Map definitions for Test models.
/// </summary>
public class TestMapDefinition : IMapDefinition
{
    /// <inheritdoc />
    public void DefineMaps(IUmbracoMapper mapper)
    {
        // Test mappings
        mapper.Define<AiTest, TestResponseModel>((_, _) => new TestResponseModel(), MapTestToResponse);
        mapper.Define<CreateTestRequestModel, AiTest>(CreateTestFactory, MapFromCreateRequest);
        mapper.Define<UpdateTestRequestModel, AiTest>((_, _) => new AiTest
        {
            Id = Guid.Empty,
            Alias = string.Empty,
            Name = string.Empty,
            TestTypeId = string.Empty,
            Target = new AiTestTarget { TargetId = string.Empty },
            TestCase = new AiTestTestCase { TestCaseJson = string.Empty }
        }, MapFromUpdateRequest);

        // Run mappings
        mapper.Define<AiTestRun, TestRunResponseModel>((_, _) => new TestRunResponseModel(), MapRunToResponse);

        // Metrics mappings
        mapper.Define<AiTestMetrics, TestMetricsResponseModel>((_, _) => new TestMetricsResponseModel(), MapMetricsToResponse);
    }

    // Factory for creating new test from request
    private static AiTest CreateTestFactory(CreateTestRequestModel source, MapperContext context)
    {
        return new AiTest
        {
            Id = Guid.Empty, // Will be generated by service
            Alias = source.Alias,
            Name = source.Name,
            Description = source.Description,
            TestTypeId = source.TestTypeId,
            Target = new AiTestTarget
            {
                TargetId = source.Target.TargetId,
                IsAlias = source.Target.IsAlias
            },
            TestCase = new AiTestTestCase
            {
                TestCaseJson = source.TestCase.TestCaseJson
            },
            Graders = source.Graders.Select(g => new AiTestGrader
            {
                Id = Guid.NewGuid(),
                GraderTypeId = g.GraderTypeId,
                Name = g.Name,
                Description = g.Description,
                ConfigJson = g.ConfigJson,
                Negate = g.Negate,
                Severity = g.Severity,
                Weight = g.Weight,
                SortOrder = g.SortOrder
            }).ToList(),
            RunCount = source.RunCount,
            Tags = source.Tags.ToList(),
            IsEnabled = source.IsEnabled
        };
    }

    // Map from CreateTestRequestModel to AiTest
    private static void MapFromCreateRequest(CreateTestRequestModel source, AiTest target, MapperContext context)
    {
        // All properties set in factory
    }

    // Map from UpdateTestRequestModel to existing AiTest
    private static void MapFromUpdateRequest(UpdateTestRequestModel source, AiTest target, MapperContext context)
    {
        target.Name = source.Name;
        target.Description = source.Description;
        target.TestTypeId = source.TestTypeId;
        target.Target = new AiTestTarget
        {
            TargetId = source.Target.TargetId,
            IsAlias = source.Target.IsAlias
        };
        target.TestCase = new AiTestTestCase
        {
            TestCaseJson = source.TestCase.TestCaseJson
        };

        // Map graders (preserve IDs for existing, generate for new)
        target.Graders = source.Graders.Select(g => new AiTestGrader
        {
            Id = g.Id == Guid.Empty ? Guid.NewGuid() : g.Id,
            GraderTypeId = g.GraderTypeId,
            Name = g.Name,
            Description = g.Description,
            ConfigJson = g.ConfigJson,
            Negate = g.Negate,
            Severity = g.Severity,
            Weight = g.Weight,
            SortOrder = g.SortOrder
        }).ToList();

        target.RunCount = source.RunCount;
        target.Tags = source.Tags.ToList();
        target.IsEnabled = source.IsEnabled;
    }

    // Map AiTest to TestResponseModel
    private static void MapTestToResponse(AiTest source, TestResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.TestTypeId = source.TestTypeId;
        target.Target = new TestTargetModel
        {
            TargetId = source.Target.TargetId,
            IsAlias = source.Target.IsAlias
        };
        target.TestCase = new TestCaseModel
        {
            TestCaseJson = source.TestCase.TestCaseJson
        };
        target.Graders = source.Graders.Select(g => new TestGraderModel
        {
            Id = g.Id,
            GraderTypeId = g.GraderTypeId,
            Name = g.Name,
            Description = g.Description,
            ConfigJson = g.ConfigJson,
            Negate = g.Negate,
            Severity = g.Severity,
            Weight = g.Weight,
            SortOrder = g.SortOrder
        }).ToList();
        target.RunCount = source.RunCount;
        target.Tags = source.Tags.ToList();
        target.IsEnabled = source.IsEnabled;
        target.BaselineRunId = source.BaselineRunId;
        target.DateCreated = source.DateCreated;
        target.DateModified = source.DateModified;
        target.CreatedByUserId = source.CreatedByUserId;
        target.ModifiedByUserId = source.ModifiedByUserId;
        target.Version = source.Version;
    }

    // Map AiTestRun to TestRunResponseModel
    private static void MapRunToResponse(AiTestRun source, TestRunResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.TestId = source.TestId;
        target.TestVersion = source.TestVersion;
        target.RunNumber = source.RunNumber;
        target.ProfileId = source.ProfileId;
        target.ContextIdsJson = source.ContextIdsJson;
        target.ExecutedAt = source.ExecutedAt;
        target.ExecutedByUserId = source.ExecutedByUserId;
        target.DurationMs = source.DurationMs;
        target.Status = (int)source.Status;
        target.ErrorMessage = source.ErrorMessage;

        if (source.Outcome is not null)
        {
            target.Outcome = new TestOutcomeModel
            {
                OutputType = (int)source.Outcome.OutputType,
                OutputValue = source.Outcome.OutputValue,
                FinishReason = source.Outcome.FinishReason,
                InputTokens = source.Outcome.InputTokens,
                OutputTokens = source.Outcome.OutputTokens
            };
        }

        if (source.Transcript is not null)
        {
            target.Transcript = new TestTranscriptModel
            {
                Id = source.Transcript.Id,
                RunId = source.Transcript.RunId,
                MessagesJson = source.Transcript.MessagesJson,
                ToolCallsJson = source.Transcript.ToolCallsJson,
                ReasoningJson = source.Transcript.ReasoningJson,
                TimingJson = source.Transcript.TimingJson,
                FinalOutputJson = source.Transcript.FinalOutputJson
            };
        }

        target.GraderResults = source.GraderResults.Select(r => new TestGraderResultModel
        {
            GraderId = r.GraderId,
            Passed = r.Passed,
            Score = r.Score,
            ActualValue = r.ActualValue,
            ExpectedValue = r.ExpectedValue,
            FailureMessage = r.FailureMessage,
            MetadataJson = r.MetadataJson
        }).ToList();

        target.BatchId = source.BatchId;
    }

    // Map AiTestMetrics to TestMetricsResponseModel
    private static void MapMetricsToResponse(AiTestMetrics source, TestMetricsResponseModel target, MapperContext context)
    {
        target.TestId = source.TestId;
        target.TotalRuns = source.TotalRuns;
        target.PassedRuns = source.PassedRuns;
        target.PassAtK = source.PassAtK;
        target.PassToTheK = source.PassToTheK;
        target.RunIds = source.RunIds.ToList();
    }
}
