using Umbraco.Ai.Agent.Core.Agents;
using Umbraco.Ai.Agent.Web.Api.Management.Agent.Models;
using Umbraco.Cms.Core.Mapping;
using Umbraco.Cms.Core.Strings;

namespace Umbraco.Ai.Agent.Web.Api.Management.Agent.Mapping;

/// <summary>
/// UmbracoMapper definitions for agent models.
/// </summary>
public class AgentMapDefinition(IShortStringHelper shortStringHelper) : IMapDefinition
{
    /// <inheritdoc />
    public void DefineMaps(IUmbracoMapper mapper)
    {
        // Response mappings (domain -> response)
        mapper.Define<AiAgent, AgentResponseModel>((_, _) => new AgentResponseModel(), MapToResponse);
        mapper.Define<AiAgent, AgentItemResponseModel>((_, _) => new AgentItemResponseModel(), MapToItemResponse);

        // Request mappings (request -> domain)
        // Create: Factory sets init-only properties (Id, Alias, DateCreated), Map sets the rest
        mapper.Define<CreateAgentRequestModel, AiAgent>(CreateAgentFactory, MapFromCreateRequest);
        // Update: Maps onto existing entity, so init-only properties are already set
        mapper.Define<UpdateAgentRequestModel, AiAgent>((_, _) => new AiAgent
        {
            Id = Guid.Empty,
            Alias = string.Empty,
            Name = string.Empty,
            Content = string.Empty
        }, MapFromUpdateRequest);
    }

    private AiAgent CreateAgentFactory(CreateAgentRequestModel source, MapperContext context)
    {
        var now = DateTime.UtcNow;
        return new AiAgent
        {
            Id = Guid.Empty, // Will be generated by the service
            Alias = !string.IsNullOrWhiteSpace(source.Alias)
                ? source.Alias
                : shortStringHelper.CleanStringForSafeAlias(source.Alias),
            Name = source.Name,
            Content = source.Content,
            DateCreated = now
        };
    }

    // Umbraco.Code.MapAll -Id -DateCreated
    private static void MapFromCreateRequest(CreateAgentRequestModel source, AiAgent target, MapperContext context)
    {
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Content = source.Content;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.Tags = source.Tags?.ToList() ?? [];
        target.IsActive = true;
        target.Scope = MapScopeModelToDomain(source.Scope);
        target.DateModified = DateTime.UtcNow;
    }

    // Umbraco.Code.MapAll -Id -DateCreated -DateModified
    private static void MapFromUpdateRequest(UpdateAgentRequestModel source, AiAgent target, MapperContext context)
    {
        // Note: Id, DateCreated, and DateModified are preserved from the existing entity
        // DateModified will be set by the service
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Content = source.Content;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.Tags = source.Tags?.ToList() ?? [];
        target.IsActive = source.IsActive;
        target.Scope = MapScopeModelToDomain(source.Scope);
    }

    // Umbraco.Code.MapAll
    private static void MapToResponse(AiAgent source, AgentResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.Content = source.Content;
        target.ProfileId = source.ProfileId;
        target.Tags = source.Tags;
        target.IsActive = source.IsActive;
        target.Scope = MapScopeDomainToModel(source.Scope);
        target.DateCreated = source.DateCreated;
        target.DateModified = source.DateModified;
    }

    // Umbraco.Code.MapAll
    private static void MapToItemResponse(AiAgent source, AgentItemResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.IsActive = source.IsActive;
    }

    private static AiAgentScope? MapScopeModelToDomain(ScopeModel? model)
    {
        if (model is null)
        {
            return null;
        }

        return new AiAgentScope
        {
            AllowRules = model.AllowRules.Select(MapScopeRuleModelToDomain).ToList(),
            DenyRules = model.DenyRules.Select(MapScopeRuleModelToDomain).ToList()
        };
    }

    private static AiAgentScopeRule MapScopeRuleModelToDomain(ScopeRuleModel model)
    {
        return new AiAgentScopeRule
        {
            PropertyEditorUiAliases = model.PropertyEditorUiAliases?.ToList(),
            PropertyAliases = model.PropertyAliases?.ToList(),
            ContentTypeAliases = model.ContentTypeAliases?.ToList()
        };
    }

    private static ScopeModel? MapScopeDomainToModel(AiAgentScope? scope)
    {
        if (scope is null)
        {
            return null;
        }

        return new ScopeModel
        {
            AllowRules = scope.AllowRules.Select(MapScopeRuleDomainToModel),
            DenyRules = scope.DenyRules.Select(MapScopeRuleDomainToModel)
        };
    }

    private static ScopeRuleModel MapScopeRuleDomainToModel(AiAgentScopeRule rule)
    {
        return new ScopeRuleModel
        {
            PropertyEditorUiAliases = rule.PropertyEditorUiAliases,
            PropertyAliases = rule.PropertyAliases,
            ContentTypeAliases = rule.ContentTypeAliases
        };
    }
}
