using Umbraco.Ai.Core.Models;
using Umbraco.Ai.Core.Profiles;
using Umbraco.Ai.Web.Api.Management.Common.Models;
using Umbraco.Ai.Web.Api.Management.Profile.Models;
using Umbraco.Cms.Core.Mapping;

namespace Umbraco.Ai.Web.Api.Management.Profile.Mapping;

/// <summary>
/// Map definitions for Profile models.
/// </summary>
public class ProfileMapDefinition : IMapDefinition
{
    /// <inheritdoc />
    public void DefineMaps(IUmbracoMapper mapper)
    {
        // Response mappings (domain -> response)
        mapper.Define<AiProfile, ProfileResponseModel>((_, _) => new ProfileResponseModel(), MapToResponse);
        mapper.Define<AiProfile, ProfileItemResponseModel>((_, _) => new ProfileItemResponseModel(), MapToItemResponse);

        // Request mappings (request -> domain)
        // Create: Factory sets init-only properties (Id, Capability), Map sets the rest
        mapper.Define<CreateProfileRequestModel, AiProfile>(CreateProfileFactory, MapFromCreateRequest);
        // Update: Maps onto existing entity, so init-only properties are already set
        mapper.Define<UpdateProfileRequestModel, AiProfile>((_, _) => new AiProfile
        {
            Id = Guid.Empty,
            Alias = string.Empty,
            Name = string.Empty,
            ConnectionId = Guid.Empty
        }, MapFromUpdateRequest);
    }

    private static AiProfile CreateProfileFactory(CreateProfileRequestModel source, MapperContext context)
    {
        var capability = Enum.TryParse<AiCapability>(source.Capability, true, out var cap)
            ? cap
            : AiCapability.Chat;
        return new AiProfile
        {
            Id = Guid.Empty, // Will be generated by the service
            Alias = source.Alias,
            Name = source.Name,
            Capability = capability,
            ConnectionId = source.ConnectionId
        };
    }

    // Umbraco.Code.MapAll -Id -Capability
    private static void MapFromCreateRequest(CreateProfileRequestModel source, AiProfile target, MapperContext context)
    {
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Model = new AiModelRef(source.Model.ProviderId, source.Model.ModelId);
        target.ConnectionId = source.ConnectionId;
        target.Settings = MapSettingsFromRequest(target.Capability, source.Settings);
        target.Tags = source.Tags;
    }

    // Umbraco.Code.MapAll -Id -Capability
    private static void MapFromUpdateRequest(UpdateProfileRequestModel source, AiProfile target, MapperContext context)
    {
        // Note: Id, Capability are preserved from the existing entity
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Model = new AiModelRef(source.Model.ProviderId, source.Model.ModelId);
        target.ConnectionId = source.ConnectionId;
        target.Settings = MapSettingsFromRequest(target.Capability, source.Settings);
        target.Tags = source.Tags;
    }

    // Umbraco.Code.MapAll
    private static void MapToResponse(AiProfile source, ProfileResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.ConnectionId = source.ConnectionId;
        target.Capability = source.Capability.ToString();
        target.Model = context.Map<ModelRefModel>(source.Model);
        target.Settings = MapSettingsToResponse(source);
        target.Tags = source.Tags;
    }

    // Umbraco.Code.MapAll
    private static void MapToItemResponse(AiProfile source, ProfileItemResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Capability = source.Capability.ToString();
        target.Model = context.Map<ModelRefModel>(source.Model);
    }

    private static ProfileSettingsModel? MapSettingsToResponse(AiProfile source)
    {
        return source.Settings switch
        {
            AiChatProfileSettings chat => new ChatProfileSettingsModel
            {
                Temperature = chat.Temperature,
                MaxTokens = chat.MaxTokens,
                SystemPromptTemplate = chat.SystemPromptTemplate
            },
            AiEmbeddingProfileSettings => new EmbeddingProfileSettingsModel(),
            _ => null
        };
    }

    private static IAiProfileSettings? MapSettingsFromRequest(AiCapability capability, ProfileSettingsModel? settings)
    {
        return capability switch
        {
            AiCapability.Chat when settings is ChatProfileSettingsModel chat => new AiChatProfileSettings
            {
                Temperature = chat.Temperature,
                MaxTokens = chat.MaxTokens,
                SystemPromptTemplate = chat.SystemPromptTemplate
            },
            AiCapability.Chat => new AiChatProfileSettings(),
            AiCapability.Embedding => new AiEmbeddingProfileSettings(),
            _ => null
        };
    }
}
