using Umbraco.Ai.Prompt.Core.Prompts;
using Umbraco.Ai.Prompt.Web.Api.Management.Prompt.Models;
using Umbraco.Cms.Core.Mapping;
using Umbraco.Cms.Core.Strings;

namespace Umbraco.Ai.Prompt.Web.Api.Management.Prompt.Mapping;

/// <summary>
/// UmbracoMapper definitions for prompt models.
/// </summary>
public class PromptMapDefinition(IShortStringHelper shortStringHelper) : IMapDefinition
{
    /// <inheritdoc />
    public void DefineMaps(IUmbracoMapper mapper)
    {
        // Response mappings (domain -> response)
        mapper.Define<AiPrompt, PromptResponseModel>((_, _) => new PromptResponseModel(), MapToResponse);
        mapper.Define<AiPrompt, PromptItemResponseModel>((_, _) => new PromptItemResponseModel(), MapToItemResponse);

        // Request mappings (request -> domain)
        // Create: Factory sets init-only properties (Id, Alias, DateCreated), Map sets the rest
        mapper.Define<CreatePromptRequestModel, AiPrompt>(CreatePromptFactory, MapFromCreateRequest);
        // Update: Maps onto existing entity, so init-only properties are already set
        mapper.Define<UpdatePromptRequestModel, AiPrompt>((_, _) => new AiPrompt
        {
            Id = Guid.Empty,
            Alias = string.Empty,
            Name = string.Empty,
            Content = string.Empty
        }, MapFromUpdateRequest);
    }

    private AiPrompt CreatePromptFactory(CreatePromptRequestModel source, MapperContext context)
    {
        var now = DateTime.UtcNow;
        return new AiPrompt
        {
            Id = Guid.Empty, // Will be generated by the service
            Alias = !string.IsNullOrWhiteSpace(source.Alias)
                ? source.Alias
                : shortStringHelper.CleanStringForSafeAlias(source.Alias),
            Name = source.Name,
            Content = source.Content,
            DateCreated = now
        };
    }

    // Umbraco.Code.MapAll -Id -DateCreated
    private static void MapFromCreateRequest(CreatePromptRequestModel source, AiPrompt target, MapperContext context)
    {
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Content = source.Content;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.Tags = source.Tags?.ToList() ?? [];
        target.IsActive = true;
        target.Visibility = MapVisibilityModelToDomain(source.Visibility);
        target.DateModified = DateTime.UtcNow;
    }

    // Umbraco.Code.MapAll -Id -DateCreated -DateModified
    private static void MapFromUpdateRequest(UpdatePromptRequestModel source, AiPrompt target, MapperContext context)
    {
        // Note: Id, DateCreated, and DateModified are preserved from the existing entity
        // DateModified will be set by the service
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Content = source.Content;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.Tags = source.Tags?.ToList() ?? [];
        target.IsActive = source.IsActive;
        target.Visibility = MapVisibilityModelToDomain(source.Visibility);
    }

    // Umbraco.Code.MapAll
    private static void MapToResponse(AiPrompt source, PromptResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.Content = source.Content;
        target.ProfileId = source.ProfileId;
        target.Tags = source.Tags;
        target.IsActive = source.IsActive;
        target.Visibility = MapVisibilityDomainToModel(source.Visibility);
        target.DateCreated = source.DateCreated;
        target.DateModified = source.DateModified;
    }

    // Umbraco.Code.MapAll
    private static void MapToItemResponse(AiPrompt source, PromptItemResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.IsActive = source.IsActive;
    }

    private static AiPromptVisibility? MapVisibilityModelToDomain(VisibilityModel? model)
    {
        if (model is null)
        {
            return null;
        }

        return new AiPromptVisibility
        {
            ShowRules = model.ShowRules.Select(MapVisibilityRuleModelToDomain).ToList(),
            HideRules = model.HideRules.Select(MapVisibilityRuleModelToDomain).ToList()
        };
    }

    private static AiPromptVisibilityRule MapVisibilityRuleModelToDomain(VisibilityRuleModel model)
    {
        return new AiPromptVisibilityRule
        {
            PropertyEditorUiAliases = model.PropertyEditorUiAliases?.ToList(),
            PropertyAliases = model.PropertyAliases?.ToList(),
            DocumentTypeAliases = model.DocumentTypeAliases?.ToList()
        };
    }

    private static VisibilityModel? MapVisibilityDomainToModel(AiPromptVisibility? visibility)
    {
        if (visibility is null)
        {
            return null;
        }

        return new VisibilityModel
        {
            ShowRules = visibility.ShowRules.Select(MapVisibilityRuleDomainToModel),
            HideRules = visibility.HideRules.Select(MapVisibilityRuleDomainToModel)
        };
    }

    private static VisibilityRuleModel MapVisibilityRuleDomainToModel(AiPromptVisibilityRule rule)
    {
        return new VisibilityRuleModel
        {
            PropertyEditorUiAliases = rule.PropertyEditorUiAliases,
            PropertyAliases = rule.PropertyAliases,
            DocumentTypeAliases = rule.DocumentTypeAliases
        };
    }
}
