// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteConnectionsByIdData, DeleteConnectionsByIdErrors, DeleteConnectionsByIdResponses, DeleteProfilesByIdData, DeleteProfilesByIdErrors, DeleteProfilesByIdResponses, GetConnectionsByIdData, GetConnectionsByIdErrors, GetConnectionsByIdResponses, GetConnectionsData, GetConnectionsErrors, GetConnectionsResponses, GetProfilesAliasByAliasData, GetProfilesAliasByAliasErrors, GetProfilesAliasByAliasResponses, GetProfilesByIdData, GetProfilesByIdErrors, GetProfilesByIdResponses, GetProfilesData, GetProfilesErrors, GetProfilesResponses, GetProvidersByIdData, GetProvidersByIdErrors, GetProvidersByIdModelsData, GetProvidersByIdModelsErrors, GetProvidersByIdModelsResponses, GetProvidersByIdResponses, GetProvidersData, GetProvidersErrors, GetProvidersResponses, PostChatCompleteData, PostChatCompleteErrors, PostChatCompleteResponses, PostChatStreamData, PostChatStreamErrors, PostChatStreamResponses, PostConnectionsByIdTestData, PostConnectionsByIdTestErrors, PostConnectionsByIdTestResponses, PostConnectionsData, PostConnectionsErrors, PostConnectionsResponses, PostEmbeddingGenerateData, PostEmbeddingGenerateErrors, PostEmbeddingGenerateResponses, PostProfilesData, PostProfilesErrors, PostProfilesResponses, PutConnectionsByIdData, PutConnectionsByIdErrors, PutConnectionsByIdResponses, PutProfilesByIdData, PutProfilesByIdErrors, PutProfilesByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class ChatService {
    public static postChatComplete<ThrowOnError extends boolean = false>(options?: Options<PostChatCompleteData, ThrowOnError>) {
        return (options?.client ?? client).post<PostChatCompleteResponses, PostChatCompleteErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/chat/complete',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static postChatStream<ThrowOnError extends boolean = false>(options?: Options<PostChatStreamData, ThrowOnError>) {
        return (options?.client ?? client).post<PostChatStreamResponses, PostChatStreamErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/chat/stream',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
}

export class ConnectionsService {
    public static getConnections<ThrowOnError extends boolean = false>(options?: Options<GetConnectionsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetConnectionsResponses, GetConnectionsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/connections',
            ...options
        });
    }
    
    public static postConnections<ThrowOnError extends boolean = false>(options?: Options<PostConnectionsData, ThrowOnError>) {
        return (options?.client ?? client).post<PostConnectionsResponses, PostConnectionsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/connections',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteConnectionsById<ThrowOnError extends boolean = false>(options: Options<DeleteConnectionsByIdData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteConnectionsByIdResponses, DeleteConnectionsByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/connections/{id}',
            ...options
        });
    }
    
    public static getConnectionsById<ThrowOnError extends boolean = false>(options: Options<GetConnectionsByIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetConnectionsByIdResponses, GetConnectionsByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/connections/{id}',
            ...options
        });
    }
    
    public static putConnectionsById<ThrowOnError extends boolean = false>(options: Options<PutConnectionsByIdData, ThrowOnError>) {
        return (options.client ?? client).put<PutConnectionsByIdResponses, PutConnectionsByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/connections/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static postConnectionsByIdTest<ThrowOnError extends boolean = false>(options: Options<PostConnectionsByIdTestData, ThrowOnError>) {
        return (options.client ?? client).post<PostConnectionsByIdTestResponses, PostConnectionsByIdTestErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/connections/{id}/test',
            ...options
        });
    }
}

export class EmbeddingService {
    public static postEmbeddingGenerate<ThrowOnError extends boolean = false>(options?: Options<PostEmbeddingGenerateData, ThrowOnError>) {
        return (options?.client ?? client).post<PostEmbeddingGenerateResponses, PostEmbeddingGenerateErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/embedding/generate',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
}

export class ProfilesService {
    public static getProfiles<ThrowOnError extends boolean = false>(options?: Options<GetProfilesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetProfilesResponses, GetProfilesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/profiles',
            ...options
        });
    }
    
    public static postProfiles<ThrowOnError extends boolean = false>(options?: Options<PostProfilesData, ThrowOnError>) {
        return (options?.client ?? client).post<PostProfilesResponses, PostProfilesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/profiles',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deleteProfilesById<ThrowOnError extends boolean = false>(options: Options<DeleteProfilesByIdData, ThrowOnError>) {
        return (options.client ?? client).delete<DeleteProfilesByIdResponses, DeleteProfilesByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/profiles/{id}',
            ...options
        });
    }
    
    public static getProfilesById<ThrowOnError extends boolean = false>(options: Options<GetProfilesByIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetProfilesByIdResponses, GetProfilesByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/profiles/{id}',
            ...options
        });
    }
    
    public static putProfilesById<ThrowOnError extends boolean = false>(options: Options<PutProfilesByIdData, ThrowOnError>) {
        return (options.client ?? client).put<PutProfilesByIdResponses, PutProfilesByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/profiles/{id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static getProfilesAliasByAlias<ThrowOnError extends boolean = false>(options: Options<GetProfilesAliasByAliasData, ThrowOnError>) {
        return (options.client ?? client).get<GetProfilesAliasByAliasResponses, GetProfilesAliasByAliasErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/profiles/alias/{alias}',
            ...options
        });
    }
}

export class ProvidersService {
    public static getProviders<ThrowOnError extends boolean = false>(options?: Options<GetProvidersData, ThrowOnError>) {
        return (options?.client ?? client).get<GetProvidersResponses, GetProvidersErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/providers',
            ...options
        });
    }
    
    public static getProvidersById<ThrowOnError extends boolean = false>(options: Options<GetProvidersByIdData, ThrowOnError>) {
        return (options.client ?? client).get<GetProvidersByIdResponses, GetProvidersByIdErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/providers/{id}',
            ...options
        });
    }
    
    public static getProvidersByIdModels<ThrowOnError extends boolean = false>(options: Options<GetProvidersByIdModelsData, ThrowOnError>) {
        return (options.client ?? client).get<GetProvidersByIdModelsResponses, GetProvidersByIdModelsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/providers/{id}/models',
            ...options
        });
    }
}
