// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44363' | (string & {});
};

export type ChatMessageModel = {
    role: string;
    content: string;
};

export type ChatProfileSettingsModel = ProfileSettingsModel & {
    $type: string;
    temperature?: number | null;
    maxTokens?: number | null;
    systemPromptTemplate?: string | null;
};

export type ChatRequestModel = {
    profileId?: string | null;
    messages: Array<ChatMessageModel>;
};

export type ChatResponseModel = {
    message: ChatMessageModel;
    finishReason?: string | null;
    usage?: ChatUsageModel | null;
};

export type ChatUsageModel = {
    inputTokens?: number | null;
    outputTokens?: number | null;
    totalTokens?: number | null;
};

export type ConnectionItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    providerId: string;
    isActive: boolean;
};

export type ConnectionResponseModel = {
    id: string;
    alias: string;
    name: string;
    providerId: string;
    settings?: unknown;
    isActive: boolean;
    dateCreated: string;
    dateModified: string;
};

export type ConnectionTestResultModel = {
    success: boolean;
    errorMessage?: string | null;
};

export type CreateConnectionRequestModel = {
    alias: string;
    name: string;
    providerId: string;
    settings?: unknown;
    isActive: boolean;
};

export type CreateProfileRequestModel = {
    alias: string;
    name: string;
    capability: string;
    model: ModelRefModel;
    connectionId: string;
    settings?: ChatProfileSettingsModel | EmbeddingProfileSettingsModel | null;
    tags: Array<string>;
};

export type EmbeddingItemModel = {
    index: number;
    vector: Array<number>;
};

export type EmbeddingProfileSettingsModel = ProfileSettingsModel & {
    $type: string;
};

export type EmbeddingResponseModel = {
    embeddings: Array<EmbeddingItemModel>;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type GenerateEmbeddingRequestModel = {
    profileId?: string | null;
    values: Array<string>;
};

export type ModelDescriptorResponseModel = {
    model: ModelRefModel;
    name: string;
    metadata?: {
        [key: string]: string;
    } | null;
};

export type ModelRefModel = {
    providerId: string;
    modelId: string;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type PagedConnectionItemResponseModel = {
    total: number;
    items: Array<ConnectionItemResponseModel>;
};

export type PagedProfileItemResponseModel = {
    total: number;
    items: Array<ProfileItemResponseModel>;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type ProfileItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    capability: string;
    model?: ModelRefModel | null;
};

export type ProfileResponseModel = {
    id: string;
    alias: string;
    name: string;
    capability: string;
    model?: ModelRefModel | null;
    connectionId: string;
    settings?: ChatProfileSettingsModel | EmbeddingProfileSettingsModel | null;
    tags: Array<string>;
};

export type ProfileSettingsModel = {
    [key: string]: never;
};

export type ProviderItemResponseModel = {
    id: string;
    name: string;
    capabilities: Array<string>;
};

export type ProviderResponseModel = {
    id: string;
    name: string;
    capabilities: Array<string>;
    settingDefinitions: Array<SettingDefinitionModel>;
};

export type SettingDefinitionModel = {
    key: string;
    label: string;
    description?: string | null;
    editorUiAlias?: string | null;
    editorConfig?: unknown;
    defaultValue?: unknown;
    sortOrder: number;
    isRequired: boolean;
};

export type UpdateConnectionRequestModel = {
    alias: string;
    name: string;
    settings?: unknown;
    isActive: boolean;
};

export type UpdateProfileRequestModel = {
    alias: string;
    name: string;
    model: ModelRefModel;
    connectionId: string;
    settings?: ChatProfileSettingsModel | EmbeddingProfileSettingsModel | null;
    tags: Array<string>;
};

export type CompleteChatData = {
    body?: ChatRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/chat/complete';
};

export type CompleteChatErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type CompleteChatError = CompleteChatErrors[keyof CompleteChatErrors];

export type CompleteChatResponses = {
    /**
     * OK
     */
    200: ChatResponseModel;
};

export type CompleteChatResponse = CompleteChatResponses[keyof CompleteChatResponses];

export type StreamChatData = {
    body?: ChatRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/chat/stream';
};

export type StreamChatErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type StreamChatError = StreamChatErrors[keyof StreamChatErrors];

export type StreamChatResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetConnectionsData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        providerId?: string;
        capability?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ai/management/api/v1/connections';
};

export type GetConnectionsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetConnectionsResponses = {
    /**
     * OK
     */
    200: PagedConnectionItemResponseModel;
};

export type GetConnectionsResponse = GetConnectionsResponses[keyof GetConnectionsResponses];

export type CreateConnectionData = {
    body?: CreateConnectionRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections';
};

export type CreateConnectionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type CreateConnectionError = CreateConnectionErrors[keyof CreateConnectionErrors];

export type CreateConnectionResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteConnectionByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/{id}';
};

export type DeleteConnectionByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteConnectionByIdError = DeleteConnectionByIdErrors[keyof DeleteConnectionByIdErrors];

export type DeleteConnectionByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetConnectionByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/{id}';
};

export type GetConnectionByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetConnectionByIdError = GetConnectionByIdErrors[keyof GetConnectionByIdErrors];

export type GetConnectionByIdResponses = {
    /**
     * OK
     */
    200: ConnectionResponseModel;
};

export type GetConnectionByIdResponse = GetConnectionByIdResponses[keyof GetConnectionByIdResponses];

export type UpdateConnectionByIdData = {
    body?: UpdateConnectionRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/{id}';
};

export type UpdateConnectionByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateConnectionByIdError = UpdateConnectionByIdErrors[keyof UpdateConnectionByIdErrors];

export type UpdateConnectionByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetModelsByConnectionIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        capability?: string;
    };
    url: '/umbraco/ai/management/api/v1/connections/{id}/models';
};

export type GetModelsByConnectionIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetModelsByConnectionIdError = GetModelsByConnectionIdErrors[keyof GetModelsByConnectionIdErrors];

export type GetModelsByConnectionIdResponses = {
    /**
     * OK
     */
    200: Array<ModelDescriptorResponseModel>;
};

export type GetModelsByConnectionIdResponse = GetModelsByConnectionIdResponses[keyof GetModelsByConnectionIdResponses];

export type TestConnectionByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/{id}/test';
};

export type TestConnectionByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type TestConnectionByIdError = TestConnectionByIdErrors[keyof TestConnectionByIdErrors];

export type TestConnectionByIdResponses = {
    /**
     * OK
     */
    200: ConnectionTestResultModel;
};

export type TestConnectionByIdResponse = TestConnectionByIdResponses[keyof TestConnectionByIdResponses];

export type GetAvailableCapabilitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/capabilities';
};

export type GetAvailableCapabilitiesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAvailableCapabilitiesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetAvailableCapabilitiesResponse = GetAvailableCapabilitiesResponses[keyof GetAvailableCapabilitiesResponses];

export type GenerateEmbeddingsData = {
    body?: GenerateEmbeddingRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/embeddings/generate';
};

export type GenerateEmbeddingsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GenerateEmbeddingsError = GenerateEmbeddingsErrors[keyof GenerateEmbeddingsErrors];

export type GenerateEmbeddingsResponses = {
    /**
     * OK
     */
    200: EmbeddingResponseModel;
};

export type GenerateEmbeddingsResponse = GenerateEmbeddingsResponses[keyof GenerateEmbeddingsResponses];

export type GetProfilesData = {
    body?: never;
    path?: never;
    query?: {
        capability?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ai/management/api/v1/profiles';
};

export type GetProfilesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetProfilesResponses = {
    /**
     * OK
     */
    200: PagedProfileItemResponseModel;
};

export type GetProfilesResponse = GetProfilesResponses[keyof GetProfilesResponses];

export type CreateProfileData = {
    body?: CreateProfileRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/profiles';
};

export type CreateProfileErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type CreateProfileError = CreateProfileErrors[keyof CreateProfileErrors];

export type CreateProfileResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteProfileByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/profiles/{id}';
};

export type DeleteProfileByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteProfileByIdError = DeleteProfileByIdErrors[keyof DeleteProfileByIdErrors];

export type DeleteProfileByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetProfileByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/profiles/{id}';
};

export type GetProfileByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetProfileByIdError = GetProfileByIdErrors[keyof GetProfileByIdErrors];

export type GetProfileByIdResponses = {
    /**
     * OK
     */
    200: ProfileResponseModel;
};

export type GetProfileByIdResponse = GetProfileByIdResponses[keyof GetProfileByIdResponses];

export type UpdateProfileByIdData = {
    body?: UpdateProfileRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/profiles/{id}';
};

export type UpdateProfileByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateProfileByIdError = UpdateProfileByIdErrors[keyof UpdateProfileByIdErrors];

export type UpdateProfileByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetProfileByAliasData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/profiles/alias/{alias}';
};

export type GetProfileByAliasErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetProfileByAliasError = GetProfileByAliasErrors[keyof GetProfileByAliasErrors];

export type GetProfileByAliasResponses = {
    /**
     * OK
     */
    200: ProfileResponseModel;
};

export type GetProfileByAliasResponse = GetProfileByAliasResponses[keyof GetProfileByAliasResponses];

export type GetProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/providers';
};

export type GetProvidersErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetProvidersResponses = {
    /**
     * OK
     */
    200: Array<ProviderItemResponseModel>;
};

export type GetProvidersResponse = GetProvidersResponses[keyof GetProvidersResponses];

export type GetProviderByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/providers/{id}';
};

export type GetProviderByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetProviderByIdError = GetProviderByIdErrors[keyof GetProviderByIdErrors];

export type GetProviderByIdResponses = {
    /**
     * OK
     */
    200: ProviderResponseModel;
};

export type GetProviderByIdResponse = GetProviderByIdResponses[keyof GetProviderByIdResponses];
