// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44363' | (string & {});
};

export type ChatMessageModel = {
    role: string;
    content: string;
};

export type ChatRequestModel = {
    profileId?: string | null;
    messages: Array<ChatMessageModel>;
};

export type ChatResponseModel = {
    message: ChatMessageModel;
    finishReason?: string | null;
    usage?: ChatUsageModel | null;
};

export type ChatUsageModel = {
    inputTokens?: number | null;
    outputTokens?: number | null;
    totalTokens?: number | null;
};

export type ConnectionItemResponseModel = {
    id: string;
    name: string;
    providerId: string;
    isActive: boolean;
};

export type ConnectionResponseModel = {
    id: string;
    alias: string;
    name: string;
    providerId: string;
    settings?: unknown;
    isActive: boolean;
    dateCreated: string;
    dateModified: string;
};

export type ConnectionTestResultModel = {
    success: boolean;
    errorMessage?: string | null;
};

export type CreateConnectionRequestModel = {
    alias: string;
    name: string;
    providerId: string;
    settings?: unknown;
    isActive: boolean;
};

export type CreateProfileRequestModel = {
    alias: string;
    name: string;
    capability: string;
    model: ModelRefModel;
    connectionId: string;
    temperature?: number | null;
    maxTokens?: number | null;
    systemPromptTemplate?: string | null;
    tags: Array<string>;
};

export type EmbeddingItemModel = {
    index: number;
    vector: Array<number>;
};

export type EmbeddingResponseModel = {
    embeddings: Array<EmbeddingItemModel>;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type GenerateEmbeddingRequestModel = {
    profileId?: string | null;
    values: Array<string>;
};

export type ModelDescriptorResponseModel = {
    model: ModelRefModel;
    name: string;
    metadata?: {
        [key: string]: string;
    } | null;
};

export type ModelRefModel = {
    providerId: string;
    modelId: string;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type PagedConnectionItemResponseModel = {
    total: number;
    items: Array<ConnectionItemResponseModel>;
};

export type PagedProfileItemResponseModel = {
    total: number;
    items: Array<ProfileItemResponseModel>;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type ProfileItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    capability: string;
    model?: ModelRefModel | null;
};

export type ProfileResponseModel = {
    id: string;
    alias: string;
    name: string;
    capability: string;
    model?: ModelRefModel | null;
    connectionId: string;
    temperature?: number | null;
    maxTokens?: number | null;
    systemPromptTemplate?: string | null;
    tags: Array<string>;
};

export type ProviderItemResponseModel = {
    id: string;
    name: string;
    capabilities: Array<string>;
};

export type ProviderResponseModel = {
    id: string;
    name: string;
    capabilities: Array<string>;
    settingDefinitions: Array<SettingDefinitionModel>;
};

export type SettingDefinitionModel = {
    key: string;
    label: string;
    description?: string | null;
    editorUiAlias?: string | null;
    editorConfig?: unknown;
    defaultValue?: unknown;
    sortOrder: number;
    isRequired: boolean;
};

export type UpdateConnectionRequestModel = {
    alias: string;
    name: string;
    settings?: unknown;
    isActive: boolean;
};

export type UpdateProfileRequestModel = {
    name: string;
    model: ModelRefModel;
    connectionId: string;
    temperature?: number | null;
    maxTokens?: number | null;
    systemPromptTemplate?: string | null;
    tags: Array<string>;
};

export type PostChatCompleteData = {
    body?: ChatRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/chat/complete';
};

export type PostChatCompleteErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostChatCompleteError = PostChatCompleteErrors[keyof PostChatCompleteErrors];

export type PostChatCompleteResponses = {
    /**
     * OK
     */
    200: ChatResponseModel;
};

export type PostChatCompleteResponse = PostChatCompleteResponses[keyof PostChatCompleteResponses];

export type PostChatStreamData = {
    body?: ChatRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/chat/stream';
};

export type PostChatStreamErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostChatStreamError = PostChatStreamErrors[keyof PostChatStreamErrors];

export type PostChatStreamResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetConnectionsData = {
    body?: never;
    path?: never;
    query?: {
        providerId?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ai/management/api/v1/connections';
};

export type GetConnectionsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetConnectionsResponses = {
    /**
     * OK
     */
    200: PagedConnectionItemResponseModel;
};

export type GetConnectionsResponse = GetConnectionsResponses[keyof GetConnectionsResponses];

export type PostConnectionsData = {
    body?: CreateConnectionRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections';
};

export type PostConnectionsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostConnectionsError = PostConnectionsErrors[keyof PostConnectionsErrors];

export type PostConnectionsResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteConnectionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/{id}';
};

export type DeleteConnectionsByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteConnectionsByIdError = DeleteConnectionsByIdErrors[keyof DeleteConnectionsByIdErrors];

export type DeleteConnectionsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetConnectionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/{id}';
};

export type GetConnectionsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetConnectionsByIdError = GetConnectionsByIdErrors[keyof GetConnectionsByIdErrors];

export type GetConnectionsByIdResponses = {
    /**
     * OK
     */
    200: ConnectionResponseModel;
};

export type GetConnectionsByIdResponse = GetConnectionsByIdResponses[keyof GetConnectionsByIdResponses];

export type PutConnectionsByIdData = {
    body?: UpdateConnectionRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/{id}';
};

export type PutConnectionsByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutConnectionsByIdError = PutConnectionsByIdErrors[keyof PutConnectionsByIdErrors];

export type PutConnectionsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostConnectionsByIdTestData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/{id}/test';
};

export type PostConnectionsByIdTestErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostConnectionsByIdTestError = PostConnectionsByIdTestErrors[keyof PostConnectionsByIdTestErrors];

export type PostConnectionsByIdTestResponses = {
    /**
     * OK
     */
    200: ConnectionTestResultModel;
};

export type PostConnectionsByIdTestResponse = PostConnectionsByIdTestResponses[keyof PostConnectionsByIdTestResponses];

export type PostEmbeddingGenerateData = {
    body?: GenerateEmbeddingRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/embedding/generate';
};

export type PostEmbeddingGenerateErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostEmbeddingGenerateError = PostEmbeddingGenerateErrors[keyof PostEmbeddingGenerateErrors];

export type PostEmbeddingGenerateResponses = {
    /**
     * OK
     */
    200: EmbeddingResponseModel;
};

export type PostEmbeddingGenerateResponse = PostEmbeddingGenerateResponses[keyof PostEmbeddingGenerateResponses];

export type GetProfilesData = {
    body?: never;
    path?: never;
    query?: {
        capability?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ai/management/api/v1/profiles';
};

export type GetProfilesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetProfilesResponses = {
    /**
     * OK
     */
    200: PagedProfileItemResponseModel;
};

export type GetProfilesResponse = GetProfilesResponses[keyof GetProfilesResponses];

export type PostProfilesData = {
    body?: CreateProfileRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/profiles';
};

export type PostProfilesErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PostProfilesError = PostProfilesErrors[keyof PostProfilesErrors];

export type PostProfilesResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteProfilesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/profiles/{id}';
};

export type DeleteProfilesByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteProfilesByIdError = DeleteProfilesByIdErrors[keyof DeleteProfilesByIdErrors];

export type DeleteProfilesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetProfilesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/profiles/{id}';
};

export type GetProfilesByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetProfilesByIdError = GetProfilesByIdErrors[keyof GetProfilesByIdErrors];

export type GetProfilesByIdResponses = {
    /**
     * OK
     */
    200: ProfileResponseModel;
};

export type GetProfilesByIdResponse = GetProfilesByIdResponses[keyof GetProfilesByIdResponses];

export type PutProfilesByIdData = {
    body?: UpdateProfileRequestModel;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/profiles/{id}';
};

export type PutProfilesByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PutProfilesByIdError = PutProfilesByIdErrors[keyof PutProfilesByIdErrors];

export type PutProfilesByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetProfilesAliasByAliasData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/profiles/alias/{alias}';
};

export type GetProfilesAliasByAliasErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetProfilesAliasByAliasError = GetProfilesAliasByAliasErrors[keyof GetProfilesAliasByAliasErrors];

export type GetProfilesAliasByAliasResponses = {
    /**
     * OK
     */
    200: ProfileResponseModel;
};

export type GetProfilesAliasByAliasResponse = GetProfilesAliasByAliasResponses[keyof GetProfilesAliasByAliasResponses];

export type GetProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/providers';
};

export type GetProvidersErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetProvidersResponses = {
    /**
     * OK
     */
    200: Array<ProviderItemResponseModel>;
};

export type GetProvidersResponse = GetProvidersResponses[keyof GetProvidersResponses];

export type GetProvidersByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/providers/{id}';
};

export type GetProvidersByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetProvidersByIdError = GetProvidersByIdErrors[keyof GetProvidersByIdErrors];

export type GetProvidersByIdResponses = {
    /**
     * OK
     */
    200: ProviderResponseModel;
};

export type GetProvidersByIdResponse = GetProvidersByIdResponses[keyof GetProvidersByIdResponses];

export type GetProvidersByIdModelsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: {
        connectionId?: string;
        capability?: string;
    };
    url: '/umbraco/ai/management/api/v1/providers/{id}/models';
};

export type GetProvidersByIdModelsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetProvidersByIdModelsError = GetProvidersByIdModelsErrors[keyof GetProvidersByIdModelsErrors];

export type GetProvidersByIdModelsResponses = {
    /**
     * OK
     */
    200: Array<ModelDescriptorResponseModel>;
};

export type GetProvidersByIdModelsResponse = GetProvidersByIdModelsResponses[keyof GetProvidersByIdModelsResponses];
