// NOTE: `KnowledgeSetResponseModel` is generated by `npm run generate-client` from the
// `GET /v1/knowledge-set` Management API endpoint (see AllKnowledgeSetController). Until the client is
// regenerated against a running demo site, this import is unresolved and typechecking will fail — this
// is expected/deferred, not a code defect (see Phase 2 validation notes).
import type { KnowledgeSetResponseModel } from "../api";
import { UAI_KNOWLEDGE_SET_ENTITY_TYPE } from "./constants.js";
import type { UaiKnowledgeSetItemModel } from "./types.js";

export const UaiKnowledgeSetTypeMapper = {
    toItemModel(response: KnowledgeSetResponseModel): UaiKnowledgeSetItemModel {
        return {
            unique: response.id,
            entityType: UAI_KNOWLEDGE_SET_ENTITY_TYPE,
            name: response.name,
            description: response.description ?? null,
            icon: response.icon ?? null,
            itemCount: response.itemCount ?? 0,
        };
    },
};
