// NOTE: `KnowledgeSetResponseModel` / `KnowledgeSetDetailResponseModel` are generated by
// `npm run generate-client` from the `GET /v1/knowledge-sets[/{id}]` Management API endpoints (see
// AllKnowledgeSetController / ByIdKnowledgeSetController). Until the client is regenerated against a
// running demo site, these imports are unresolved and typechecking will fail — this is
// expected/deferred, not a code defect (see Phase 2/3 validation notes).
import type { KnowledgeSetResponseModel, KnowledgeSetDetailResponseModel } from "../api";
import { UAI_KNOWLEDGE_SET_ENTITY_TYPE } from "./constants.js";
import type { UaiKnowledgeSetDetailModel, UaiKnowledgeSetItemModel } from "./types.js";

export const UaiKnowledgeSetTypeMapper = {
    toItemModel(response: KnowledgeSetResponseModel): UaiKnowledgeSetItemModel {
        return {
            unique: response.id,
            entityType: UAI_KNOWLEDGE_SET_ENTITY_TYPE,
            name: response.name,
            description: response.description ?? null,
            icon: response.icon ?? null,
            itemCount: response.itemCount ?? 0,
        };
    },

    toDetailModel(response: KnowledgeSetDetailResponseModel): UaiKnowledgeSetDetailModel {
        return {
            unique: response.id,
            entityType: UAI_KNOWLEDGE_SET_ENTITY_TYPE,
            name: response.name,
            description: response.description ?? null,
            icon: response.icon ?? null,
            items: (response.items ?? []).map((item) => ({
                name: item.name,
                description: item.description ?? null,
                content: item.content,
            })),
        };
    },
};
