using Umbraco.AI.Prompt.Core.Prompts;
using Umbraco.AI.Prompt.Web.Api.Management.Prompt.Models;
using Umbraco.Cms.Core.Mapping;
using Umbraco.Cms.Core.Strings;

namespace Umbraco.AI.Prompt.Web.Api.Management.Prompt.Mapping;

/// <summary>
/// UmbracoMapper definitions for prompt models.
/// </summary>
internal class PromptMapDefinition(IShortStringHelper shortStringHelper) : IMapDefinition
{
    /// <inheritdoc />
    public void DefineMaps(IUmbracoMapper mapper)
    {
        // Response mappings (domain -> response)
        mapper.Define<AIPrompt, PromptResponseModel>((_, _) => new PromptResponseModel(), MapToResponse);
        mapper.Define<AIPrompt, PromptItemResponseModel>((_, _) => new PromptItemResponseModel(), MapToItemResponse);

        // Request mappings (request -> domain)
        // Create: Factory sets init-only properties (Id, Alias, DateCreated), Map sets the rest
        mapper.Define<CreatePromptRequestModel, AIPrompt>(CreatePromptFactory, MapFromCreateRequest);
        // Update: Maps onto existing entity, so init-only properties are already set
        mapper.Define<UpdatePromptRequestModel, AIPrompt>((_, _) => new AIPrompt
        {
            Id = Guid.Empty,
            Alias = string.Empty,
            Name = string.Empty,
            Instructions = string.Empty
        }, MapFromUpdateRequest);
    }

    private AIPrompt CreatePromptFactory(CreatePromptRequestModel source, MapperContext context)
    {
        var now = DateTime.UtcNow;
        return new AIPrompt
        {
            Id = Guid.Empty, // Will be generated by the service
            Alias = !string.IsNullOrWhiteSpace(source.Alias)
                ? source.Alias
                : shortStringHelper.CleanStringForSafeAlias(source.Alias),
            Name = source.Name,
            Instructions = source.Instructions,
            DateCreated = now
        };
    }

    // Umbraco.Code.MapAll -Id -DateCreated -Version -CreatedByUserId -ModifiedByUserId
    private static void MapFromCreateRequest(CreatePromptRequestModel source, AIPrompt target, MapperContext context)
    {
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Instructions = source.Instructions;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.ContextIds = source.ContextIds?.ToList() ?? [];
        target.Tags = source.Tags?.ToList() ?? [];
        target.IsActive = true;
        target.IncludeEntityContext = source.IncludeEntityContext;
        target.Scope = MapScopeModelToDomain(source.Scope);
        target.DateModified = DateTime.UtcNow;
    }

    // Umbraco.Code.MapAll -Id -DateCreated -DateModified -Version -CreatedByUserId -ModifiedByUserId
    private static void MapFromUpdateRequest(UpdatePromptRequestModel source, AIPrompt target, MapperContext context)
    {
        // Note: Id, DateCreated, and DateModified are preserved from the existing entity
        // DateModified will be set by the service
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Instructions = source.Instructions;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.ContextIds = source.ContextIds?.ToList() ?? [];
        target.Tags = source.Tags?.ToList() ?? [];
        target.IsActive = source.IsActive;
        target.IncludeEntityContext = source.IncludeEntityContext;
        target.Scope = MapScopeModelToDomain(source.Scope);
    }

    // Umbraco.Code.MapAll -CreatedByUserId -ModifiedByUserId
    private static void MapToResponse(AIPrompt source, PromptResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.Instructions = source.Instructions;
        target.ProfileId = source.ProfileId;
        target.ContextIds = source.ContextIds;
        target.Tags = source.Tags;
        target.IsActive = source.IsActive;
        target.IncludeEntityContext = source.IncludeEntityContext;
        target.Scope = MapScopeDomainToModel(source.Scope);
        target.DateCreated = source.DateCreated;
        target.DateModified = source.DateModified;
        target.Version = source.Version;
    }

    // Umbraco.Code.MapAll -Version -CreatedByUserId -ModifiedByUserId
    private static void MapToItemResponse(AIPrompt source, PromptItemResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.IsActive = source.IsActive;
        target.DateCreated = source.DateCreated;
        target.DateModified = source.DateModified;
    }

    private static AIPromptScope? MapScopeModelToDomain(ScopeModel? model)
    {
        if (model is null)
        {
            return null;
        }

        return new AIPromptScope
        {
            AllowRules = model.AllowRules.Select(MapScopeRuleModelToDomain).ToList(),
            DenyRules = model.DenyRules.Select(MapScopeRuleModelToDomain).ToList()
        };
    }

    private static AIPromptScopeRule MapScopeRuleModelToDomain(ScopeRuleModel model)
    {
        return new AIPromptScopeRule
        {
            PropertyEditorUiAliases = model.PropertyEditorUiAliases?.ToList(),
            PropertyAliases = model.PropertyAliases?.ToList(),
            ContentTypeAliases = model.ContentTypeAliases?.ToList()
        };
    }

    private static ScopeModel? MapScopeDomainToModel(AIPromptScope? scope)
    {
        if (scope is null)
        {
            return null;
        }

        return new ScopeModel
        {
            AllowRules = scope.AllowRules.Select(MapScopeRuleDomainToModel),
            DenyRules = scope.DenyRules.Select(MapScopeRuleDomainToModel)
        };
    }

    private static ScopeRuleModel MapScopeRuleDomainToModel(AIPromptScopeRule rule)
    {
        return new ScopeRuleModel
        {
            PropertyEditorUiAliases = rule.PropertyEditorUiAliases,
            PropertyAliases = rule.PropertyAliases,
            ContentTypeAliases = rule.ContentTypeAliases
        };
    }
}
