// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreatePromptData, CreatePromptErrors, CreatePromptResponses, DeletePromptData, DeletePromptErrors, DeletePromptResponses, ExecutePromptData, ExecutePromptErrors, ExecutePromptResponses, GetAllPromptsData, GetAllPromptsErrors, GetAllPromptsResponses, GetDocumentTypeAliasesData, GetDocumentTypeAliasesErrors, GetDocumentTypeAliasesResponses, GetPromptByIdOrAliasData, GetPromptByIdOrAliasErrors, GetPromptByIdOrAliasResponses, GetPropertyAliasesData, GetPropertyAliasesErrors, GetPropertyAliasesResponses, UpdatePromptData, UpdatePromptErrors, UpdatePromptResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class PromptsService {
    public static getAllPrompts<ThrowOnError extends boolean = false>(options?: Options<GetAllPromptsData, ThrowOnError>) {
        return (options?.client ?? client).get<GetAllPromptsResponses, GetAllPromptsErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/prompts',
            ...options
        });
    }
    
    public static createPrompt<ThrowOnError extends boolean = false>(options?: Options<CreatePromptData, ThrowOnError>) {
        return (options?.client ?? client).post<CreatePromptResponses, CreatePromptErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/prompts',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static deletePrompt<ThrowOnError extends boolean = false>(options: Options<DeletePromptData, ThrowOnError>) {
        return (options.client ?? client).delete<DeletePromptResponses, DeletePromptErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/prompts/{promptIdOrAlias}',
            ...options
        });
    }
    
    public static getPromptByIdOrAlias<ThrowOnError extends boolean = false>(options: Options<GetPromptByIdOrAliasData, ThrowOnError>) {
        return (options.client ?? client).get<GetPromptByIdOrAliasResponses, GetPromptByIdOrAliasErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/prompts/{promptIdOrAlias}',
            ...options
        });
    }
    
    public static updatePrompt<ThrowOnError extends boolean = false>(options: Options<UpdatePromptData, ThrowOnError>) {
        return (options.client ?? client).put<UpdatePromptResponses, UpdatePromptErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/prompts/{promptIdOrAlias}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    public static executePrompt<ThrowOnError extends boolean = false>(options: Options<ExecutePromptData, ThrowOnError>) {
        return (options.client ?? client).post<ExecutePromptResponses, ExecutePromptErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/prompts/{promptIdOrAlias}/execute',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}

export class UtilsService {
    public static getDocumentTypeAliases<ThrowOnError extends boolean = false>(options?: Options<GetDocumentTypeAliasesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetDocumentTypeAliasesResponses, GetDocumentTypeAliasesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/utils/document-type-aliases',
            ...options
        });
    }
    
    public static getPropertyAliases<ThrowOnError extends boolean = false>(options?: Options<GetPropertyAliasesData, ThrowOnError>) {
        return (options?.client ?? client).get<GetPropertyAliasesResponses, GetPropertyAliasesErrors, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/ai/management/api/v1/utils/property-aliases',
            ...options
        });
    }
}
