using Umbraco.AI.Core.Models;
using Umbraco.AI.Core.Profiles;
using Umbraco.AI.Web.Api.Management.Common.Models;
using Umbraco.AI.Web.Api.Management.Profile.Models;
using Umbraco.Cms.Core.Mapping;

namespace Umbraco.AI.Web.Api.Management.Profile.Mapping;

/// <summary>
/// Map definitions for Profile models.
/// </summary>
public class ProfileMapDefinition : IMapDefinition
{
    /// <inheritdoc />
    public void DefineMaps(IUmbracoMapper mapper)
    {
        // Response mappings (domain -> response)
        mapper.Define<AIProfile, ProfileResponseModel>((_, _) => new ProfileResponseModel(), MapToResponse);
        mapper.Define<AIProfile, ProfileItemResponseModel>((_, _) => new ProfileItemResponseModel(), MapToItemResponse);

        // Request mappings (request -> domain)
        // Create: Factory sets init-only properties (Id, Capability), Map sets the rest
        mapper.Define<CreateProfileRequestModel, AIProfile>(CreateProfileFactory, MapFromCreateRequest);
        // Update: Maps onto existing entity, so init-only properties are already set
        mapper.Define<UpdateProfileRequestModel, AIProfile>((_, _) => new AIProfile
        {
            Id = Guid.Empty,
            Alias = string.Empty,
            Name = string.Empty,
            ConnectionId = Guid.Empty
        }, MapFromUpdateRequest);
    }

    private static AIProfile CreateProfileFactory(CreateProfileRequestModel source, MapperContext context)
    {
        var capability = Enum.TryParse<AICapability>(source.Capability, true, out var cap)
            ? cap
            : AICapability.Chat;
        return new AIProfile
        {
            Id = Guid.Empty, // Will be generated by the service
            Alias = source.Alias,
            Name = source.Name,
            Capability = capability,
            ConnectionId = source.ConnectionId
        };
    }

    // Umbraco.Code.MapAll -Id -Capability -DateCreated -DateModified -Version -CreatedByUserId -ModifiedByUserId
    private static void MapFromCreateRequest(CreateProfileRequestModel source, AIProfile target, MapperContext context)
    {
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Model = new AIModelRef(source.Model.ProviderId, source.Model.ModelId);
        target.ConnectionId = source.ConnectionId;
        target.Settings = MapSettingsFromRequest(target.Capability, source.Settings);
        target.Tags = source.Tags;
    }

    // Umbraco.Code.MapAll -Id -Capability -DateCreated -DateModified -Version -CreatedByUserId -ModifiedByUserId
    private static void MapFromUpdateRequest(UpdateProfileRequestModel source, AIProfile target, MapperContext context)
    {
        // Note: Id, Capability are preserved from the existing entity
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Model = new AIModelRef(source.Model.ProviderId, source.Model.ModelId);
        target.ConnectionId = source.ConnectionId;
        target.Settings = MapSettingsFromRequest(target.Capability, source.Settings);
        target.Tags = source.Tags;
    }

    // Umbraco.Code.MapAll
    private static void MapToResponse(AIProfile source, ProfileResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.ConnectionId = source.ConnectionId;
        target.Capability = source.Capability.ToString();
        target.Model = context.Map<ModelRefModel>(source.Model);
        target.Settings = MapSettingsToResponse(source);
        target.Tags = source.Tags;
        target.DateCreated = source.DateCreated;
        target.DateModified = source.DateModified;
        target.Version = source.Version;
    }

    // Umbraco.Code.MapAll -DateCreated -DateModified -Version
    private static void MapToItemResponse(AIProfile source, ProfileItemResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Capability = source.Capability.ToString();
        target.Model = context.Map<ModelRefModel>(source.Model);
        target.DateCreated = source.DateCreated;
        target.DateModified = source.DateModified;
    }

    private static ProfileSettingsModel? MapSettingsToResponse(AIProfile source)
    {
        return source.Settings switch
        {
            AIChatProfileSettings chat => new ChatProfileSettingsModel
            {
                Temperature = chat.Temperature,
                MaxTokens = chat.MaxTokens,
                SystemPromptTemplate = chat.SystemPromptTemplate,
                ContextIds = chat.ContextIds
            },
            AIEmbeddingProfileSettings => new EmbeddingProfileSettingsModel(),
            _ => null
        };
    }

    private static IAiProfileSettings? MapSettingsFromRequest(AICapability capability, ProfileSettingsModel? settings)
    {
        return capability switch
        {
            AICapability.Chat when settings is ChatProfileSettingsModel chat => new AIChatProfileSettings
            {
                Temperature = chat.Temperature,
                MaxTokens = chat.MaxTokens,
                SystemPromptTemplate = chat.SystemPromptTemplate,
                ContextIds = chat.ContextIds
            },
            AICapability.Chat => new AIChatProfileSettings(),
            AICapability.Embedding => new AIEmbeddingProfileSettings(),
            _ => null
        };
    }
}
