using Umbraco.Ai.Core.Connections;
using Umbraco.Ai.Web.Api.Management.Connection.Models;
using Umbraco.Cms.Core.Mapping;

namespace Umbraco.Ai.Web.Api.Management.Connection.Mapping;

/// <summary>
/// Map definitions for Connection models.
/// </summary>
public class ConnectionMapDefinition : IMapDefinition
{
    /// <inheritdoc />
    public void DefineMaps(IUmbracoMapper mapper)
    {
        // Response mappings (domain -> response)
        mapper.Define<AiConnection, ConnectionResponseModel>((_, _) => new ConnectionResponseModel(), MapToResponse);
        mapper.Define<AiConnection, ConnectionItemResponseModel>((_, _) => new ConnectionItemResponseModel(), MapToItemResponse);

        // Request mappings (request -> domain)
        // Create: Factory sets init-only properties (Id, Alias, ProviderId, DateCreated), Map sets the rest
        mapper.Define<CreateConnectionRequestModel, AiConnection>(CreateConnectionFactory, MapFromCreateRequest);
        // Update: Maps onto existing entity, so init-only properties are already set
        mapper.Define<UpdateConnectionRequestModel, AiConnection>((_, _) => new AiConnection
        {
            Id = Guid.Empty,
            Alias = string.Empty,
            Name = string.Empty,
            ProviderId = string.Empty
        }, MapFromUpdateRequest);
    }

    private static AiConnection CreateConnectionFactory(CreateConnectionRequestModel source, MapperContext context)
    {
        return new AiConnection
        {
            Id = Guid.Empty, // Will be generated by the service
            Alias = source.Alias,
            Name = source.Name,
            ProviderId = source.ProviderId,
            DateCreated = DateTime.UtcNow
        };
    }

    // Umbraco.Code.MapAll -Id -Alias -ProviderId -DateCreated -CreatedByUserId -ModifiedByUserId
    private static void MapFromCreateRequest(CreateConnectionRequestModel source, AiConnection target, MapperContext context)
    {
        target.Name = source.Name;
        target.Settings = source.Settings;
        target.IsActive = source.IsActive;
        target.DateModified = DateTime.UtcNow;
    }

    // Umbraco.Code.MapAll -Id -Alias -ProviderId -DateCreated -DateModified -CreatedByUserId -ModifiedByUserId
    private static void MapFromUpdateRequest(UpdateConnectionRequestModel source, AiConnection target, MapperContext context)
    {
        // Note: Id, Alias, ProviderId, DateCreated are preserved from the existing entity
        // DateModified will be set by the service
        target.Name = source.Name;
        target.Settings = source.Settings;
        target.IsActive = source.IsActive;
    }

    // Umbraco.Code.MapAll
    private static void MapToResponse(AiConnection source, ConnectionResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.ProviderId = source.ProviderId;
        target.Settings = source.Settings;
        target.IsActive = source.IsActive;
        target.DateCreated = source.DateCreated;
        target.DateModified = source.DateModified;
    }

    // Umbraco.Code.MapAll
    private static void MapToItemResponse(AiConnection source, ConnectionItemResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.ProviderId = source.ProviderId;
        target.IsActive = source.IsActive;
    }
}
