using Umbraco.Ai.Agent.Core.Agents;
using Umbraco.Ai.Agent.Web.Api.Management.Agent.Models;
using Umbraco.Cms.Core.Mapping;
using Umbraco.Cms.Core.Strings;

namespace Umbraco.Ai.Agent.Web.Api.Management.Agent.Mapping;

/// <summary>
/// UmbracoMapper definitions for agent models.
/// </summary>
internal class AgentMapDefinition(IShortStringHelper shortStringHelper) : IMapDefinition
{
    /// <inheritdoc />
    public void DefineMaps(IUmbracoMapper mapper)
    {
        // Response mappings (domain -> response)
        mapper.Define<AiAgent, AgentResponseModel>((_, _) => new AgentResponseModel(), MapToResponse);
        mapper.Define<AiAgent, AgentItemResponseModel>((_, _) => new AgentItemResponseModel(), MapToItemResponse);

        // Request mappings (request -> domain)
        // Create: Factory sets init-only properties (Id, Alias), Map sets the rest
        mapper.Define<CreateAgentRequestModel, AiAgent>(CreateAgentFactory, MapFromCreateRequest);
        // Update: Maps onto existing entity, so init-only properties are already set
        mapper.Define<UpdateAgentRequestModel, AiAgent>((_, _) => new AiAgent
        {
            Id = Guid.Empty,
            Alias = string.Empty,
            Name = string.Empty
        }, MapFromUpdateRequest);
    }

    private AiAgent CreateAgentFactory(CreateAgentRequestModel source, MapperContext context)
    {
        return new AiAgent
        {
            Id = Guid.Empty, // Will be generated by the service
            Alias = !string.IsNullOrWhiteSpace(source.Alias)
                ? source.Alias
                : shortStringHelper.CleanStringForSafeAlias(source.Alias),
            Name = source.Name,
            ProfileId = source.ProfileId
        };
    }

    // Umbraco.Code.MapAll -Id -DateCreated -DateModified -Version -CreatedByUserId -ModifiedByUserId
    private static void MapFromCreateRequest(CreateAgentRequestModel source, AiAgent target, MapperContext context)
    {
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.ContextIds = source.ContextIds?.ToList() ?? [];
        target.Instructions = source.Instructions;
        target.IsActive = true;
    }

    // Umbraco.Code.MapAll -Id -DateCreated -DateModified -Version -CreatedByUserId -ModifiedByUserId
    private static void MapFromUpdateRequest(UpdateAgentRequestModel source, AiAgent target, MapperContext context)
    {
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.ContextIds = source.ContextIds?.ToList() ?? [];
        target.Instructions = source.Instructions;
        target.IsActive = source.IsActive;
    }

    // Umbraco.Code.MapAll -DateCreated -DateModified -Version -CreatedByUserId -ModifiedByUserId
    private static void MapToResponse(AiAgent source, AgentResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.ContextIds = source.ContextIds;
        target.Instructions = source.Instructions;
        target.IsActive = source.IsActive;
    }

    // Umbraco.Code.MapAll -DateCreated -DateModified -Version -CreatedByUserId -ModifiedByUserId
    private static void MapToItemResponse(AiAgent source, AgentItemResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.ContextIds = source.ContextIds;
        target.IsActive = source.IsActive;
    }
}
