using Umbraco.AI.Agent.Core.Agents;
using Umbraco.AI.Agent.Core.Scopes;
using Umbraco.AI.Agent.Web.Api.Management.Agent.Models;
using Umbraco.Cms.Core.Mapping;
using Umbraco.Cms.Core.Strings;

namespace Umbraco.AI.Agent.Web.Api.Management.Agent.Mapping;

/// <summary>
/// UmbracoMapper definitions for agent models.
/// </summary>
internal class AgentMapDefinition(IShortStringHelper shortStringHelper) : IMapDefinition
{
    /// <inheritdoc />
    public void DefineMaps(IUmbracoMapper mapper)
    {
        // Response mappings (domain -> response)
        mapper.Define<AIAgent, AgentResponseModel>((_, _) => new AgentResponseModel(), MapToResponse);
        mapper.Define<AIAgent, AgentItemResponseModel>((_, _) => new AgentItemResponseModel(), MapToItemResponse);

        // Request mappings (request -> domain)
        // Create: Factory sets init-only properties (Id, Alias), Map sets the rest
        mapper.Define<CreateAgentRequestModel, AIAgent>(CreateAgentFactory, MapFromCreateRequest);
        // Update: Maps onto existing entity, so init-only properties are already set
        mapper.Define<UpdateAgentRequestModel, AIAgent>((_, _) => new AIAgent
        {
            Id = Guid.Empty,
            Alias = string.Empty,
            Name = string.Empty
        }, MapFromUpdateRequest);
        
        // Scope mappings
        mapper.Define<IAIAgentScope, AgentScopeItemResponseModel>((_, _) => new AgentScopeItemResponseModel(), MapToResponse);
    }

    private AIAgent CreateAgentFactory(CreateAgentRequestModel source, MapperContext context)
    {
        return new AIAgent
        {
            Id = Guid.Empty, // Will be generated by the service
            Alias = !string.IsNullOrWhiteSpace(source.Alias)
                ? source.Alias
                : shortStringHelper.CleanStringForSafeAlias(source.Alias),
            Name = source.Name,
            ProfileId = source.ProfileId
        };
    }

    // Umbraco.Code.MapAll -Id -DateCreated -DateModified -Version -CreatedByUserId -ModifiedByUserId
    private static void MapFromCreateRequest(CreateAgentRequestModel source, AIAgent target, MapperContext context)
    {
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.ContextIds = source.ContextIds?.ToList() ?? [];
        target.ScopeIds = source.ScopeIds?.ToList() ?? [];
        target.AllowedToolIds = source.AllowedToolIds?.ToList() ?? [];
        target.AllowedToolScopeIds = source.AllowedToolScopeIds?.ToList() ?? [];
        target.Instructions = source.Instructions;
        target.IsActive = true;
    }

    // Umbraco.Code.MapAll -Id -DateCreated -DateModified -Version -CreatedByUserId -ModifiedByUserId
    private static void MapFromUpdateRequest(UpdateAgentRequestModel source, AIAgent target, MapperContext context)
    {
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.ContextIds = source.ContextIds?.ToList() ?? [];
        target.ScopeIds = source.ScopeIds?.ToList() ?? [];
        target.AllowedToolIds = source.AllowedToolIds?.ToList() ?? [];
        target.AllowedToolScopeIds = source.AllowedToolScopeIds?.ToList() ?? [];
        target.Instructions = source.Instructions;
        target.IsActive = source.IsActive;
    }

    // Umbraco.Code.MapAll -CreatedByUserId -ModifiedByUserId
    private static void MapToResponse(AIAgent source, AgentResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.ContextIds = source.ContextIds;
        target.ScopeIds = source.ScopeIds;
        target.AllowedToolIds = source.AllowedToolIds;
        target.AllowedToolScopeIds = source.AllowedToolScopeIds;
        target.Instructions = source.Instructions;
        target.IsActive = source.IsActive;
        target.DateCreated = source.DateCreated;
        target.DateModified = source.DateModified;
        target.Version = source.Version;
    }

    // Umbraco.Code.MapAll -DateCreated -DateModified -Version -CreatedByUserId -ModifiedByUserId
    private static void MapToItemResponse(AIAgent source, AgentItemResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.ContextIds = source.ContextIds;
        target.ScopeIds = source.ScopeIds;
        target.IsActive = source.IsActive;
        target.DateCreated = source.DateCreated;
        target.DateModified = source.DateModified;
    }

    private static void MapToResponse(IAIAgentScope source, AgentScopeItemResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Icon = source.Icon;
    }
}
