using Umbraco.AI.Agent.Core.Agents;
using Umbraco.AI.Agent.Core.Surfaces;
using Umbraco.AI.Agent.Web.Api.Management.Agent.Models;
using Umbraco.Cms.Core.Mapping;
using Umbraco.Cms.Core.Strings;

namespace Umbraco.AI.Agent.Web.Api.Management.Agent.Mapping;

/// <summary>
/// UmbracoMapper definitions for agent models.
/// </summary>
internal class AgentMapDefinition(IShortStringHelper shortStringHelper) : IMapDefinition
{
    /// <inheritdoc />
    public void DefineMaps(IUmbracoMapper mapper)
    {
        // Response mappings (domain -> response)
        mapper.Define<AIAgent, AgentResponseModel>((_, _) => new AgentResponseModel(), MapToResponse);
        mapper.Define<AIAgent, AgentItemResponseModel>((_, _) => new AgentItemResponseModel(), MapToItemResponse);

        // Request mappings (request -> domain)
        // Create: Factory sets init-only properties (Id, Alias), Map sets the rest
        mapper.Define<CreateAgentRequestModel, AIAgent>(CreateAgentFactory, MapFromCreateRequest);
        // Update: Maps onto existing entity, so init-only properties are already set
        mapper.Define<UpdateAgentRequestModel, AIAgent>((_, _) => new AIAgent
        {
            Id = Guid.Empty,
            Alias = string.Empty,
            Name = string.Empty
        }, MapFromUpdateRequest);
        
        // Surface mappings
        mapper.Define<IAIAgentSurface, AgentSurfaceItemResponseModel>((_, _) => new AgentSurfaceItemResponseModel(), MapToResponse);
    }

    private AIAgent CreateAgentFactory(CreateAgentRequestModel source, MapperContext context)
    {
        return new AIAgent
        {
            Id = Guid.Empty, // Will be generated by the service
            Alias = !string.IsNullOrWhiteSpace(source.Alias)
                ? source.Alias
                : shortStringHelper.CleanStringForSafeAlias(source.Alias),
            Name = source.Name,
            ProfileId = source.ProfileId
        };
    }

    // Umbraco.Code.MapAll -Id -DateCreated -DateModified -Version -CreatedByUserId -ModifiedByUserId
    private static void MapFromCreateRequest(CreateAgentRequestModel source, AIAgent target, MapperContext context)
    {
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.ContextIds = source.ContextIds?.ToList() ?? [];
        target.SurfaceIds = source.SurfaceIds?.ToList() ?? [];
        target.Scope = MapScopeFromRequest(source.Scope);
        target.AllowedToolIds = source.AllowedToolIds?.ToList() ?? [];
        target.AllowedToolScopeIds = source.AllowedToolScopeIds?.ToList() ?? [];
        target.UserGroupPermissions = MapUserGroupPermissionsFromRequest(source.UserGroupPermissions);
        target.Instructions = source.Instructions;
        target.IsActive = true;
    }

    // Umbraco.Code.MapAll -Id -DateCreated -DateModified -Version -CreatedByUserId -ModifiedByUserId
    private static void MapFromUpdateRequest(UpdateAgentRequestModel source, AIAgent target, MapperContext context)
    {
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.ContextIds = source.ContextIds?.ToList() ?? [];
        target.SurfaceIds = source.SurfaceIds?.ToList() ?? [];
        target.Scope = MapScopeFromRequest(source.Scope);
        target.AllowedToolIds = source.AllowedToolIds?.ToList() ?? [];
        target.AllowedToolScopeIds = source.AllowedToolScopeIds?.ToList() ?? [];
        target.UserGroupPermissions = MapUserGroupPermissionsFromRequest(source.UserGroupPermissions);
        target.Instructions = source.Instructions;
        target.IsActive = source.IsActive;
    }

    // Umbraco.Code.MapAll -CreatedByUserId -ModifiedByUserId
    private static void MapToResponse(AIAgent source, AgentResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.ContextIds = source.ContextIds;
        target.SurfaceIds = source.SurfaceIds;
        target.Scope = MapContextScopeToResponse(source.Scope);
        target.AllowedToolIds = source.AllowedToolIds;
        target.AllowedToolScopeIds = source.AllowedToolScopeIds;
        target.UserGroupPermissions = MapUserGroupPermissionsToResponse(source.UserGroupPermissions);
        target.Instructions = source.Instructions;
        target.IsActive = source.IsActive;
        target.DateCreated = source.DateCreated;
        target.DateModified = source.DateModified;
        target.Version = source.Version;
    }

    // Umbraco.Code.MapAll -DateCreated -DateModified -Version -CreatedByUserId -ModifiedByUserId
    private static void MapToItemResponse(AIAgent source, AgentItemResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.ContextIds = source.ContextIds;
        target.SurfaceIds = source.SurfaceIds;
        target.AllowedToolIds = source.AllowedToolIds;
        target.AllowedToolScopeIds = source.AllowedToolScopeIds;
        target.IsActive = source.IsActive;
        target.DateCreated = source.DateCreated;
        target.DateModified = source.DateModified;
    }

    private static void MapToResponse(IAIAgentSurface source, AgentSurfaceItemResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Icon = source.Icon;
    }

    /// <summary>
    /// Maps user group permissions from request models to domain models.
    /// </summary>
    private static IReadOnlyDictionary<Guid, AIAgentUserGroupPermissions> MapUserGroupPermissionsFromRequest(
        Dictionary<Guid, AIAgentUserGroupPermissionsModel>? source)
    {
        if (source is null || source.Count == 0)
        {
            return new Dictionary<Guid, AIAgentUserGroupPermissions>();
        }

        return source.ToDictionary(
            kvp => kvp.Key,
            kvp => new AIAgentUserGroupPermissions
            {
                AllowedToolIds = kvp.Value.AllowedToolIds.ToList(),
                AllowedToolScopeIds = kvp.Value.AllowedToolScopeIds.ToList(),
                DeniedToolIds = kvp.Value.DeniedToolIds.ToList(),
                DeniedToolScopeIds = kvp.Value.DeniedToolScopeIds.ToList()
            });
    }

    /// <summary>
    /// Maps user group permissions from domain models to response models.
    /// </summary>
    private static Dictionary<Guid, AIAgentUserGroupPermissionsModel> MapUserGroupPermissionsToResponse(
        IReadOnlyDictionary<Guid, AIAgentUserGroupPermissions> source)
    {
        if (source.Count == 0)
        {
            return [];
        }

        return source.ToDictionary(
            kvp => kvp.Key,
            kvp => new AIAgentUserGroupPermissionsModel
            {
                AllowedToolIds = kvp.Value.AllowedToolIds,
                AllowedToolScopeIds = kvp.Value.AllowedToolScopeIds,
                DeniedToolIds = kvp.Value.DeniedToolIds,
                DeniedToolScopeIds = kvp.Value.DeniedToolScopeIds
            });
    }

    /// <summary>
    /// Maps agent scope from request model to domain model.
    /// </summary>
    private static AIAgentScope? MapScopeFromRequest(AIAgentScopeModel? source)
    {
        if (source is null)
        {
            return null;
        }

        return new AIAgentScope
        {
            AllowRules = source.AllowRules.Select(r => new AIAgentScopeRule
            {
                SectionAliases = r.SectionAliases?.ToList(),
                EntityTypeAliases = r.EntityTypeAliases?.ToList(),
                WorkspaceAliases = r.WorkspaceAliases?.ToList()
            }).ToList(),
            DenyRules = source.DenyRules.Select(r => new AIAgentScopeRule
            {
                SectionAliases = r.SectionAliases?.ToList(),
                EntityTypeAliases = r.EntityTypeAliases?.ToList(),
                WorkspaceAliases = r.WorkspaceAliases?.ToList()
            }).ToList()
        };
    }

    /// <summary>
    /// Maps agent scope from domain model to response model.
    /// </summary>
    private static AIAgentScopeModel? MapContextScopeToResponse(AIAgentScope? source)
    {
        if (source is null)
        {
            return null;
        }

        return new AIAgentScopeModel
        {
            AllowRules = source.AllowRules.Select(r => new AIAgentScopeRuleModel
            {
                SectionAliases = r.SectionAliases?.ToList(),
                EntityTypeAliases = r.EntityTypeAliases?.ToList(),
                WorkspaceAliases = r.WorkspaceAliases?.ToList()
            }).ToList(),
            DenyRules = source.DenyRules.Select(r => new AIAgentScopeRuleModel
            {
                SectionAliases = r.SectionAliases?.ToList(),
                EntityTypeAliases = r.EntityTypeAliases?.ToList(),
                WorkspaceAliases = r.WorkspaceAliases?.ToList()
            }).ToList()
        };
    }
}
