using Umbraco.AI.Agent.Core.Agents;
using Umbraco.AI.Agent.Core.Orchestrations;
using Umbraco.AI.Agent.Core.Surfaces;
using Umbraco.AI.Agent.Extensions;
using Umbraco.AI.Agent.Web.Api.Management.Agent.Models;
using Umbraco.Cms.Core.Mapping;
using Umbraco.Cms.Core.Strings;

namespace Umbraco.AI.Agent.Web.Api.Management.Agent.Mapping;

/// <summary>
/// UmbracoMapper definitions for agent models.
/// </summary>
internal class AgentMapDefinition(IShortStringHelper shortStringHelper) : IMapDefinition
{
    /// <inheritdoc />
    public void DefineMaps(IUmbracoMapper mapper)
    {
        // Response mappings (domain -> response)
        mapper.Define<AIAgent, AgentResponseModel>((_, _) => new AgentResponseModel(), MapToResponse);
        mapper.Define<AIAgent, AgentItemResponseModel>((_, _) => new AgentItemResponseModel(), MapToItemResponse);

        // Request mappings (request -> domain)
        // Create: Factory sets init-only properties (Id, Alias, AgentType), Map sets the rest
        mapper.Define<CreateAgentRequestModel, AIAgent>(CreateAgentFactory, MapFromCreateRequest);
        // Update: Maps onto existing entity, so init-only properties are already set
        mapper.Define<UpdateAgentRequestModel, AIAgent>((_, _) => new AIAgent
        {
            Id = Guid.Empty,
            Alias = string.Empty,
            Name = string.Empty
        }, MapFromUpdateRequest);

        // Surface mappings
        mapper.Define<IAIAgentSurface, AgentSurfaceItemResponseModel>((_, _) => new AgentSurfaceItemResponseModel(), MapToResponse);
    }

    private AIAgent CreateAgentFactory(CreateAgentRequestModel source, MapperContext context)
    {
        return new AIAgent
        {
            Id = Guid.Empty, // Will be generated by the service
            Alias = !string.IsNullOrWhiteSpace(source.Alias)
                ? source.Alias
                : shortStringHelper.CleanStringForSafeAlias(source.Alias),
            Name = source.Name,
            AgentType = ParseAgentType(source.AgentType),
            ProfileId = source.ProfileId
        };
    }

    // Umbraco.Code.MapAll -Id -AgentType -DateCreated -DateModified -Version -CreatedByUserId -ModifiedByUserId
    private static void MapFromCreateRequest(CreateAgentRequestModel source, AIAgent target, MapperContext context)
    {
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.SurfaceIds = source.SurfaceIds?.ToList() ?? [];
        target.Scope = MapScopeFromRequest(source.Scope);
        target.Config = MapConfigFromRequest(source.Config);
        target.IsActive = true;
    }

    // Umbraco.Code.MapAll -Id -AgentType -DateCreated -DateModified -Version -CreatedByUserId -ModifiedByUserId
    private static void MapFromUpdateRequest(UpdateAgentRequestModel source, AIAgent target, MapperContext context)
    {
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.ProfileId = source.ProfileId;
        target.SurfaceIds = source.SurfaceIds?.ToList() ?? [];
        target.Scope = MapScopeFromRequest(source.Scope);
        target.Config = MapConfigFromRequest(source.Config);
        target.IsActive = source.IsActive;
    }

    // Umbraco.Code.MapAll -CreatedByUserId -ModifiedByUserId
    private static void MapToResponse(AIAgent source, AgentResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.AgentType = FormatAgentType(source.AgentType);
        target.ProfileId = source.ProfileId;
        target.SurfaceIds = source.SurfaceIds;
        target.Scope = MapScopeToResponse(source.Scope);
        target.Config = MapConfigToResponse(source);
        target.IsActive = source.IsActive;
        target.DateCreated = source.DateCreated;
        target.DateModified = source.DateModified;
        target.Version = source.Version;
    }

    // Umbraco.Code.MapAll -Config -Version -CreatedByUserId -ModifiedByUserId
    private static void MapToItemResponse(AIAgent source, AgentItemResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Alias = source.Alias;
        target.Name = source.Name;
        target.Description = source.Description;
        target.AgentType = FormatAgentType(source.AgentType);
        target.ProfileId = source.ProfileId;
        target.SurfaceIds = source.SurfaceIds;
        target.Scope = MapScopeToResponse(source.Scope);
        target.IsActive = source.IsActive;
        target.DateCreated = source.DateCreated;
        target.DateModified = source.DateModified;
    }

    private static void MapToResponse(IAIAgentSurface source, AgentSurfaceItemResponseModel target, MapperContext context)
    {
        target.Id = source.Id;
        target.Icon = source.Icon;
        target.SupportedScopeDimensions = source.SupportedScopeDimensions;
    }

    #region AgentType helpers

    private static AIAgentType ParseAgentType(string agentType)
        => agentType.ToLowerInvariant() switch
        {
            "standard" => AIAgentType.Standard,
            "orchestrated" => AIAgentType.Orchestrated,
            _ => throw new ArgumentException($"Unknown agent type: {agentType}", nameof(agentType))
        };

    private static string FormatAgentType(AIAgentType agentType)
        => agentType switch
        {
            AIAgentType.Standard => "standard",
            AIAgentType.Orchestrated => "orchestrated",
            _ => throw new ArgumentOutOfRangeException(nameof(agentType), agentType, null)
        };

    #endregion

    #region Config mapping

    private static IAIAgentConfig? MapConfigFromRequest(AgentConfigModel? source)
    {
        return source switch
        {
            StandardAgentConfigModel standard => new AIStandardAgentConfig
            {
                ContextIds = standard.ContextIds?.ToList() ?? [],
                Instructions = standard.Instructions,
                AllowedToolIds = standard.AllowedToolIds?.ToList() ?? [],
                AllowedToolScopeIds = standard.AllowedToolScopeIds?.ToList() ?? [],
                UserGroupPermissions = MapUserGroupPermissionsFromRequest(standard.UserGroupPermissions)
            },
            OrchestratedAgentConfigModel orchestrated => new AIOrchestratedAgentConfig
            {
                Graph = orchestrated.Graph is not null
                    ? MapGraphFromRequest(orchestrated.Graph)
                    : new AIOrchestrationGraph()
            },
            null => null,
            _ => throw new ArgumentException($"Unknown config model type: {source.GetType().Name}", nameof(source))
        };
    }

    private static AgentConfigModel? MapConfigToResponse(AIAgent source)
    {
        return source.AgentType switch
        {
            AIAgentType.Standard when source.Config is AIStandardAgentConfig standard => new StandardAgentConfigModel
            {
                ContextIds = standard.ContextIds.ToList(),
                Instructions = standard.Instructions,
                AllowedToolIds = standard.AllowedToolIds.ToList(),
                AllowedToolScopeIds = standard.AllowedToolScopeIds.ToList(),
                UserGroupPermissions = MapUserGroupPermissionsToResponse(standard.UserGroupPermissions)
            },
            AIAgentType.Orchestrated when source.Config is AIOrchestratedAgentConfig orchestrated => new OrchestratedAgentConfigModel
            {
                Graph = MapGraphToResponse(orchestrated.Graph)
            },
            _ => null
        };
    }

    #endregion

    #region UserGroupPermissions mapping

    /// <summary>
    /// Maps user group permissions from request models to domain models.
    /// </summary>
    private static IReadOnlyDictionary<Guid, AIAgentUserGroupPermissions> MapUserGroupPermissionsFromRequest(
        Dictionary<Guid, AIAgentUserGroupPermissionsModel>? source)
    {
        if (source is null || source.Count == 0)
        {
            return new Dictionary<Guid, AIAgentUserGroupPermissions>();
        }

        return source.ToDictionary(
            kvp => kvp.Key,
            kvp => new AIAgentUserGroupPermissions
            {
                AllowedToolIds = kvp.Value.AllowedToolIds.ToList(),
                AllowedToolScopeIds = kvp.Value.AllowedToolScopeIds.ToList(),
                DeniedToolIds = kvp.Value.DeniedToolIds.ToList(),
                DeniedToolScopeIds = kvp.Value.DeniedToolScopeIds.ToList()
            });
    }

    /// <summary>
    /// Maps user group permissions from domain models to response models.
    /// </summary>
    private static Dictionary<Guid, AIAgentUserGroupPermissionsModel> MapUserGroupPermissionsToResponse(
        IReadOnlyDictionary<Guid, AIAgentUserGroupPermissions> source)
    {
        if (source.Count == 0)
        {
            return [];
        }

        return source.ToDictionary(
            kvp => kvp.Key,
            kvp => new AIAgentUserGroupPermissionsModel
            {
                AllowedToolIds = kvp.Value.AllowedToolIds,
                AllowedToolScopeIds = kvp.Value.AllowedToolScopeIds,
                DeniedToolIds = kvp.Value.DeniedToolIds,
                DeniedToolScopeIds = kvp.Value.DeniedToolScopeIds
            });
    }

    #endregion

    #region Graph mapping

    private static AIOrchestrationGraph MapGraphFromRequest(OrchestrationGraphModel source)
    {
        return new AIOrchestrationGraph
        {
            Nodes = source.Nodes.Select(n => new AIOrchestrationNode
            {
                Id = n.Id,
                Type = n.Type,
                Label = n.Label,
                X = n.X,
                Y = n.Y,
                Config = MapNodeConfigFromRequest(n.Type, n.Config)
            }).ToList<AIOrchestrationNode>(),
            Edges = source.Edges.Select(MapEdgeFromRequest).ToList<AIOrchestrationEdge>()
        };
    }

    private static AIOrchestrationEdge MapEdgeFromRequest(OrchestrationEdgeModel source)
    {
        return new AIOrchestrationEdge
        {
            Id = source.Id,
            SourceNodeId = source.SourceNodeId,
            TargetNodeId = source.TargetNodeId,
            SourceHandle = source.SourceHandle,
            TargetHandle = source.TargetHandle,
            IsDefault = source.IsDefault,
            Priority = source.Priority,
            RequiresApproval = source.RequiresApproval,
            Condition = source.Condition is not null
                ? new AIOrchestrationRouteCondition
                {
                    Label = source.Condition.Label,
                    Field = source.Condition.Field,
                    Operator = source.Condition.Operator,
                    Value = source.Condition.Value,
                }
                : null,
        };
    }

    private static IAIOrchestrationNodeConfig MapNodeConfigFromRequest(
        AIOrchestrationNodeType nodeType,
        NodeConfigModel source)
    {
        return source switch
        {
            AgentNodeConfigModel agent => new AIOrchestrationAgentNodeConfig
            {
                AgentId = agent.AgentId,
                IsManager = agent.IsManager,
            },
            ToolCallNodeConfigModel toolCall => new AIOrchestrationToolCallNodeConfig
            {
                ToolId = toolCall.ToolId,
            },
            AggregatorNodeConfigModel aggregator => new AIOrchestrationAggregatorNodeConfig
            {
                AggregationStrategy = aggregator.AggregationStrategy,
                ProfileId = aggregator.ProfileId,
            },
            CommunicationBusNodeConfigModel bus => new AIOrchestrationCommunicationBusNodeConfig
            {
                MaxIterations = bus.MaxIterations,
                TerminationMessage = bus.TerminationMessage,
            },
            RouterNodeConfigModel => new AIOrchestrationRouterNodeConfig(),
            StartNodeConfigModel => new AIOrchestrationStartNodeConfig(),
            EndNodeConfigModel => new AIOrchestrationEndNodeConfig(),
            _ => AIOrchestrationNodeConfigSerializer.CreateDefault(nodeType),
        };
    }

    private static OrchestrationGraphModel MapGraphToResponse(AIOrchestrationGraph source)
    {
        return new OrchestrationGraphModel
        {
            Nodes = source.Nodes.Select(n => new OrchestrationNodeModel
            {
                Id = n.Id,
                Type = n.Type,
                Label = n.Label,
                X = n.X,
                Y = n.Y,
                Config = MapNodeConfigToResponse(n.Config)
            }).ToList(),
            Edges = source.Edges.Select(MapEdgeToResponse).ToList()
        };
    }

    private static OrchestrationEdgeModel MapEdgeToResponse(AIOrchestrationEdge source)
    {
        return new OrchestrationEdgeModel
        {
            Id = source.Id,
            SourceNodeId = source.SourceNodeId,
            TargetNodeId = source.TargetNodeId,
            SourceHandle = source.SourceHandle,
            TargetHandle = source.TargetHandle,
            IsDefault = source.IsDefault,
            Priority = source.Priority,
            RequiresApproval = source.RequiresApproval,
            Condition = source.Condition is not null
                ? new OrchestrationRouteConditionModel
                {
                    Label = source.Condition.Label,
                    Field = source.Condition.Field,
                    Operator = source.Condition.Operator,
                    Value = source.Condition.Value,
                }
                : null,
        };
    }

    private static NodeConfigModel MapNodeConfigToResponse(IAIOrchestrationNodeConfig source)
    {
        return source switch
        {
            AIOrchestrationAgentNodeConfig agent => new AgentNodeConfigModel
            {
                AgentId = agent.AgentId,
                IsManager = agent.IsManager,
            },
            AIOrchestrationToolCallNodeConfig toolCall => new ToolCallNodeConfigModel
            {
                ToolId = toolCall.ToolId,
            },
            AIOrchestrationAggregatorNodeConfig aggregator => new AggregatorNodeConfigModel
            {
                AggregationStrategy = aggregator.AggregationStrategy,
                ProfileId = aggregator.ProfileId,
            },
            AIOrchestrationCommunicationBusNodeConfig bus => new CommunicationBusNodeConfigModel
            {
                MaxIterations = bus.MaxIterations,
                TerminationMessage = bus.TerminationMessage,
            },
            AIOrchestrationRouterNodeConfig => new RouterNodeConfigModel(),
            AIOrchestrationEndNodeConfig => new EndNodeConfigModel(),
            _ => new StartNodeConfigModel(),
        };
    }

    #endregion

    #region Scope mapping

    /// <summary>
    /// Maps agent scope from request model to domain model.
    /// </summary>
    private static AIAgentScope? MapScopeFromRequest(AIAgentScopeModel? source)
    {
        if (source is null)
        {
            return null;
        }

        return new AIAgentScope
        {
            AllowRules = source.AllowRules.Select(r => new AIAgentScopeRule
            {
                Sections = r.Sections?.ToList(),
                EntityTypes = r.EntityTypes?.ToList()
            }).ToList(),
            DenyRules = source.DenyRules.Select(r => new AIAgentScopeRule
            {
                Sections = r.Sections?.ToList(),
                EntityTypes = r.EntityTypes?.ToList()
            }).ToList()
        };
    }

    /// <summary>
    /// Maps agent scope from domain model to response model.
    /// </summary>
    private static AIAgentScopeModel? MapScopeToResponse(AIAgentScope? source)
    {
        if (source is null)
        {
            return null;
        }

        return new AIAgentScopeModel
        {
            AllowRules = source.AllowRules.Select(r => new AIAgentScopeRuleModel
            {
                Sections = r.Sections?.ToList(),
                EntityTypes = r.EntityTypes?.ToList()
            }).ToList(),
            DenyRules = source.DenyRules.Select(r => new AIAgentScopeRuleModel
            {
                Sections = r.Sections?.ToList(),
                EntityTypes = r.EntityTypes?.ToList()
            }).ToList()
        };
    }

    #endregion
}
