// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44355' | (string & {});
};

export type AuditLogDetailResponseModel = {
    id: string;
    startTime: string;
    durationMs?: number | null;
    status: string;
    userId: string;
    userName?: string | null;
    entityId?: string | null;
    capability: string;
    profileId: string;
    profileVersion: number;
    providerId: string;
    modelId: string;
    featureType?: string | null;
    featureId?: string | null;
    featureVersion?: number | null;
    parentAuditLogId?: string | null;
    inputTokens?: number | null;
    outputTokens?: number | null;
    errorMessage?: string | null;
    endTime?: string | null;
    entityType?: string | null;
    profileAlias: string;
    errorCategory?: string | null;
    totalTokens?: number | null;
    promptSnapshot?: string | null;
    responseSnapshot?: string | null;
    detailLevel: string;
    metadata?: Array<KeyValuePair2> | null;
};

export type AuditLogItemResponseModel = {
    id: string;
    startTime: string;
    durationMs?: number | null;
    status: string;
    userId: string;
    userName?: string | null;
    entityId?: string | null;
    capability: string;
    profileId: string;
    profileAlias: string;
    profileVersion: number;
    providerId: string;
    modelId: string;
    featureType?: string | null;
    featureId?: string | null;
    featureVersion?: number | null;
    parentAuditLogId?: string | null;
    inputTokens?: number | null;
    outputTokens?: number | null;
    errorMessage?: string | null;
};

export type ChatMessageModel = {
    role: string;
    content: string;
};

export type ChatProfileSettingsModel = ProfileSettingsModel & {
    $type: string;
    temperature?: number | null;
    maxTokens?: number | null;
    systemPromptTemplate?: string | null;
    contextIds: Array<string>;
};

export type ChatRequestModel = {
    messages: Array<ChatMessageModel>;
};

export type ChatResponseModel = {
    message: ChatMessageModel;
    finishReason?: string | null;
    usage?: UsageModel | null;
};

export type ConnectionItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    providerId: string;
    isActive: boolean;
    dateCreated: string;
    dateModified: string;
    version: number;
};

export type ConnectionResponseModel = {
    id: string;
    alias: string;
    name: string;
    providerId: string;
    settings?: unknown;
    isActive: boolean;
    dateCreated: string;
    dateModified: string;
    version: number;
};

export type ConnectionTestResultModel = {
    success: boolean;
    errorMessage?: string | null;
};

export type ContextItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    resourceCount: number;
    dateCreated: string;
    dateModified: string;
};

export type ContextResourceModel = {
    id: string;
    resourceTypeId: string;
    name: string;
    description?: string | null;
    sortOrder: number;
    data?: unknown;
    injectionMode: string;
};

export type ContextResourceTypeResponseModel = {
    id: string;
    name: string;
    description?: string | null;
    icon?: string | null;
    dataSchema?: EditableModelSchemaModel | null;
};

export type ContextResponseModel = {
    id: string;
    alias: string;
    name: string;
    dateCreated: string;
    dateModified: string;
    resources: Array<ContextResourceModel>;
    version: number;
};

export type CreateConnectionRequestModel = {
    alias: string;
    name: string;
    providerId: string;
    settings?: unknown;
    isActive: boolean;
};

export type CreateContextRequestModel = {
    alias: string;
    name: string;
    resources: Array<ContextResourceModel>;
};

export type CreateProfileRequestModel = {
    alias: string;
    name: string;
    capability: string;
    model: ModelRefModel;
    connectionId: string;
    settings?: ChatProfileSettingsModel | EmbeddingProfileSettingsModel | null;
    tags: Array<string>;
};

export type EditableModelFieldModel = {
    key: string;
    label: string;
    description?: string | null;
    editorUiAlias?: string | null;
    editorConfig?: unknown;
    defaultValue?: unknown;
    sortOrder: number;
    isRequired: boolean;
};

export type EditableModelSchemaModel = {
    type?: string | null;
    fields: Array<EditableModelFieldModel>;
};

export type EmbeddingItemModel = {
    index: number;
    vector: Array<number>;
};

export type EmbeddingProfileSettingsModel = ProfileSettingsModel & {
    $type: string;
};

export type EmbeddingResponseModel = {
    embeddings: Array<EmbeddingItemModel>;
};

export type EntityVersionComparisonResponseModel = {
    fromVersion: number;
    toVersion: number;
    changes: Array<PropertyChangeModel>;
};

export type EntityVersionHistoryResponseModel = {
    currentVersion: number;
    totalVersions: number;
    versions: Array<EntityVersionResponseModel>;
};

export type EntityVersionResponseModel = {
    id: string;
    entityId: string;
    version: number;
    dateCreated: string;
    createdByUserId?: string | null;
    createdByUserName?: string | null;
    changeDescription?: string | null;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type GenerateEmbeddingRequestModel = {
    profileIdOrAlias?: string | null;
    values: Array<string>;
};

export type KeyValuePair2 = {
    key?: string | null;
    value?: string | null;
};

export type ModelDescriptorResponseModel = {
    model: ModelRefModel;
    name: string;
    metadata?: {
        [key: string]: string;
    } | null;
};

export type ModelRefModel = {
    providerId: string;
    modelId: string;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type PagedAuditLogItemResponseModel = {
    total: number;
    items: Array<AuditLogItemResponseModel>;
};

export type PagedConnectionItemResponseModel = {
    total: number;
    items: Array<ConnectionItemResponseModel>;
};

export type PagedContextItemResponseModel = {
    total: number;
    items: Array<ContextItemResponseModel>;
};

export type PagedProfileItemResponseModel = {
    total: number;
    items: Array<ProfileItemResponseModel>;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type ProfileItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    capability: string;
    model?: ModelRefModel | null;
    dateCreated: string;
    dateModified: string;
};

export type ProfileResponseModel = {
    id: string;
    alias: string;
    name: string;
    capability: string;
    model?: ModelRefModel | null;
    connectionId: string;
    settings?: ChatProfileSettingsModel | EmbeddingProfileSettingsModel | null;
    tags: Array<string>;
    dateCreated: string;
    dateModified: string;
    version: number;
};

export type ProfileSettingsModel = {
    [key: string]: never;
};

export type PropertyChangeModel = {
    propertyName: string;
    oldValue?: string | null;
    newValue?: string | null;
};

export type ProviderItemResponseModel = {
    id: string;
    name: string;
    capabilities: Array<string>;
};

export type ProviderResponseModel = {
    id: string;
    name: string;
    capabilities: Array<string>;
    settingsSchema?: EditableModelSchemaModel | null;
};

export type SettingsResponseModel = {
    defaultChatProfileId?: string | null;
    defaultEmbeddingProfileId?: string | null;
};

export type UpdateConnectionRequestModel = {
    alias: string;
    name: string;
    settings?: unknown;
    isActive: boolean;
};

export type UpdateContextRequestModel = {
    alias: string;
    name: string;
    resources: Array<ContextResourceModel>;
};

export type UpdateProfileRequestModel = {
    alias: string;
    name: string;
    model: ModelRefModel;
    connectionId: string;
    settings?: ChatProfileSettingsModel | EmbeddingProfileSettingsModel | null;
    tags: Array<string>;
};

export type UpdateSettingsRequestModel = {
    defaultChatProfileId?: string | null;
    defaultEmbeddingProfileId?: string | null;
};

export type UsageBreakdownItemModel = {
    dimension: string;
    dimensionName?: string | null;
    requestCount: number;
    totalTokens: number;
    percentage: number;
};

export type UsageModel = {
    inputTokens?: number | null;
    outputTokens?: number | null;
    totalTokens?: number | null;
};

export type UsageSummaryResponseModel = {
    totalRequests: number;
    inputTokens: number;
    outputTokens: number;
    totalTokens: number;
    successCount: number;
    failureCount: number;
    successRate: number;
    averageDurationMs: number;
};

export type UsageTimeSeriesPointModel = {
    timestamp: string;
    requestCount: number;
    totalTokens: number;
    inputTokens: number;
    outputTokens: number;
    successCount: number;
    failureCount: number;
};

export type GetUsageBreakdownByModelData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
        granularity?: string;
    };
    url: '/umbraco/ai/management/api/v1/analytics/usage-by-model';
};

export type GetUsageBreakdownByModelErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUsageBreakdownByModelResponses = {
    /**
     * OK
     */
    200: Array<UsageBreakdownItemModel>;
};

export type GetUsageBreakdownByModelResponse = GetUsageBreakdownByModelResponses[keyof GetUsageBreakdownByModelResponses];

export type GetUsageBreakdownByProfileData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
        granularity?: string;
    };
    url: '/umbraco/ai/management/api/v1/analytics/usage-by-profile';
};

export type GetUsageBreakdownByProfileErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUsageBreakdownByProfileResponses = {
    /**
     * OK
     */
    200: Array<UsageBreakdownItemModel>;
};

export type GetUsageBreakdownByProfileResponse = GetUsageBreakdownByProfileResponses[keyof GetUsageBreakdownByProfileResponses];

export type GetUsageBreakdownByProviderData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
        granularity?: string;
    };
    url: '/umbraco/ai/management/api/v1/analytics/usage-by-provider';
};

export type GetUsageBreakdownByProviderErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUsageBreakdownByProviderResponses = {
    /**
     * OK
     */
    200: Array<UsageBreakdownItemModel>;
};

export type GetUsageBreakdownByProviderResponse = GetUsageBreakdownByProviderResponses[keyof GetUsageBreakdownByProviderResponses];

export type GetUsageBreakdownByUserData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
        granularity?: string;
    };
    url: '/umbraco/ai/management/api/v1/analytics/usage-by-user';
};

export type GetUsageBreakdownByUserErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUsageBreakdownByUserResponses = {
    /**
     * OK
     */
    200: Array<UsageBreakdownItemModel>;
};

export type GetUsageBreakdownByUserResponse = GetUsageBreakdownByUserResponses[keyof GetUsageBreakdownByUserResponses];

export type GetUsageSummaryData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
        granularity?: string;
    };
    url: '/umbraco/ai/management/api/v1/analytics/usage-summary';
};

export type GetUsageSummaryErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUsageSummaryResponses = {
    /**
     * OK
     */
    200: UsageSummaryResponseModel;
};

export type GetUsageSummaryResponse = GetUsageSummaryResponses[keyof GetUsageSummaryResponses];

export type GetUsageTimeSeriesData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
        granularity?: string;
    };
    url: '/umbraco/ai/management/api/v1/analytics/usage-time-series';
};

export type GetUsageTimeSeriesErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUsageTimeSeriesResponses = {
    /**
     * OK
     */
    200: Array<UsageTimeSeriesPointModel>;
};

export type GetUsageTimeSeriesResponse = GetUsageTimeSeriesResponses[keyof GetUsageTimeSeriesResponses];

export type GetAuditLogsData = {
    body?: never;
    path?: never;
    query?: {
        status?: string;
        userId?: string;
        profileId?: string;
        providerId?: string;
        entityId?: string;
        fromDate?: string;
        toDate?: string;
        searchText?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ai/management/api/v1/audit-logs';
};

export type GetAuditLogsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAuditLogsResponses = {
    /**
     * OK
     */
    200: PagedAuditLogItemResponseModel;
};

export type GetAuditLogsResponse = GetAuditLogsResponses[keyof GetAuditLogsResponses];

export type DeleteAuditLogData = {
    body?: never;
    path: {
        auditLogId: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/audit-logs/{auditLogId}';
};

export type DeleteAuditLogErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteAuditLogError = DeleteAuditLogErrors[keyof DeleteAuditLogErrors];

export type DeleteAuditLogResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteAuditLogResponse = DeleteAuditLogResponses[keyof DeleteAuditLogResponses];

export type GetAuditLogByIdentifierData = {
    body?: never;
    path: {
        auditLogId: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/audit-logs/{auditLogId}';
};

export type GetAuditLogByIdentifierErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetAuditLogByIdentifierError = GetAuditLogByIdentifierErrors[keyof GetAuditLogByIdentifierErrors];

export type GetAuditLogByIdentifierResponses = {
    /**
     * OK
     */
    200: AuditLogDetailResponseModel;
};

export type GetAuditLogByIdentifierResponse = GetAuditLogByIdentifierResponses[keyof GetAuditLogByIdentifierResponses];

export type CleanupAuditLogsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/audit-logs/cleanup';
};

export type CleanupAuditLogsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CleanupAuditLogsResponses = {
    /**
     * OK
     */
    200: number;
};

export type CleanupAuditLogsResponse = CleanupAuditLogsResponses[keyof CleanupAuditLogsResponses];

export type CompleteChatData = {
    body?: ChatRequestModel;
    headers?: {
        profileIdOrAlias?: string;
    };
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/chat/complete';
};

export type CompleteChatErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type CompleteChatError = CompleteChatErrors[keyof CompleteChatErrors];

export type CompleteChatResponses = {
    /**
     * OK
     */
    200: ChatResponseModel;
};

export type CompleteChatResponse = CompleteChatResponses[keyof CompleteChatResponses];

export type GetAllConnectionsData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        providerId?: string;
        capability?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ai/management/api/v1/connections';
};

export type GetAllConnectionsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllConnectionsResponses = {
    /**
     * OK
     */
    200: PagedConnectionItemResponseModel;
};

export type GetAllConnectionsResponse = GetAllConnectionsResponses[keyof GetAllConnectionsResponses];

export type CreateConnectionData = {
    body?: CreateConnectionRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections';
};

export type CreateConnectionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type CreateConnectionError = CreateConnectionErrors[keyof CreateConnectionErrors];

export type CreateConnectionResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteConnectionData = {
    body?: never;
    path: {
        connectionIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/{connectionIdOrAlias}';
};

export type DeleteConnectionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteConnectionError = DeleteConnectionErrors[keyof DeleteConnectionErrors];

export type DeleteConnectionResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetConnectionByIdOrAliasData = {
    body?: never;
    path: {
        connectionIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/{connectionIdOrAlias}';
};

export type GetConnectionByIdOrAliasErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetConnectionByIdOrAliasError = GetConnectionByIdOrAliasErrors[keyof GetConnectionByIdOrAliasErrors];

export type GetConnectionByIdOrAliasResponses = {
    /**
     * OK
     */
    200: ConnectionResponseModel;
};

export type GetConnectionByIdOrAliasResponse = GetConnectionByIdOrAliasResponses[keyof GetConnectionByIdOrAliasResponses];

export type UpdateConnectionData = {
    body?: UpdateConnectionRequestModel;
    path: {
        connectionIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/{connectionIdOrAlias}';
};

export type UpdateConnectionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateConnectionError = UpdateConnectionErrors[keyof UpdateConnectionErrors];

export type UpdateConnectionResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCapabilitiesData = {
    body?: never;
    path: {
        connectionIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/{connectionIdOrAlias}/capabilities';
};

export type GetCapabilitiesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetCapabilitiesError = GetCapabilitiesErrors[keyof GetCapabilitiesErrors];

export type GetCapabilitiesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetCapabilitiesResponse = GetCapabilitiesResponses[keyof GetCapabilitiesResponses];

export type GetModelsData = {
    body?: never;
    path: {
        connectionIdOrAlias: string;
    };
    query?: {
        capability?: string;
    };
    url: '/umbraco/ai/management/api/v1/connections/{connectionIdOrAlias}/models';
};

export type GetModelsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetModelsError = GetModelsErrors[keyof GetModelsErrors];

export type GetModelsResponses = {
    /**
     * OK
     */
    200: Array<ModelDescriptorResponseModel>;
};

export type GetModelsResponse = GetModelsResponses[keyof GetModelsResponses];

export type TestConnectionData = {
    body?: never;
    path: {
        connectionIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/{connectionIdOrAlias}/test';
};

export type TestConnectionErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type TestConnectionError = TestConnectionErrors[keyof TestConnectionErrors];

export type TestConnectionResponses = {
    /**
     * OK
     */
    200: ConnectionTestResultModel;
};

export type TestConnectionResponse = TestConnectionResponses[keyof TestConnectionResponses];

export type GetAllCapabilitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/capabilities';
};

export type GetAllCapabilitiesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllCapabilitiesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetAllCapabilitiesResponse = GetAllCapabilitiesResponses[keyof GetAllCapabilitiesResponses];

export type GetAllContextResourceTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/context-resource-types';
};

export type GetAllContextResourceTypesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllContextResourceTypesResponses = {
    /**
     * OK
     */
    200: Array<ContextResourceTypeResponseModel>;
};

export type GetAllContextResourceTypesResponse = GetAllContextResourceTypesResponses[keyof GetAllContextResourceTypesResponses];

export type GetContextResourceTypeByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/context-resource-types/{id}';
};

export type GetContextResourceTypeByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetContextResourceTypeByIdError = GetContextResourceTypeByIdErrors[keyof GetContextResourceTypeByIdErrors];

export type GetContextResourceTypeByIdResponses = {
    /**
     * OK
     */
    200: ContextResourceTypeResponseModel;
};

export type GetContextResourceTypeByIdResponse = GetContextResourceTypeByIdResponses[keyof GetContextResourceTypeByIdResponses];

export type GetAllContextsData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ai/management/api/v1/contexts';
};

export type GetAllContextsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllContextsResponses = {
    /**
     * OK
     */
    200: PagedContextItemResponseModel;
};

export type GetAllContextsResponse = GetAllContextsResponses[keyof GetAllContextsResponses];

export type CreateContextData = {
    body?: CreateContextRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/contexts';
};

export type CreateContextErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CreateContextError = CreateContextErrors[keyof CreateContextErrors];

export type CreateContextResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteContextData = {
    body?: never;
    path: {
        contextIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/contexts/{contextIdOrAlias}';
};

export type DeleteContextErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteContextError = DeleteContextErrors[keyof DeleteContextErrors];

export type DeleteContextResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetContextByIdOrAliasData = {
    body?: never;
    path: {
        contextIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/contexts/{contextIdOrAlias}';
};

export type GetContextByIdOrAliasErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetContextByIdOrAliasError = GetContextByIdOrAliasErrors[keyof GetContextByIdOrAliasErrors];

export type GetContextByIdOrAliasResponses = {
    /**
     * OK
     */
    200: ContextResponseModel;
};

export type GetContextByIdOrAliasResponse = GetContextByIdOrAliasResponses[keyof GetContextByIdOrAliasResponses];

export type UpdateContextData = {
    body?: UpdateContextRequestModel;
    path: {
        contextIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/contexts/{contextIdOrAlias}';
};

export type UpdateContextErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateContextError = UpdateContextErrors[keyof UpdateContextErrors];

export type UpdateContextResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GenerateEmbeddingsData = {
    body?: GenerateEmbeddingRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/embeddings/generate';
};

export type GenerateEmbeddingsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GenerateEmbeddingsError = GenerateEmbeddingsErrors[keyof GenerateEmbeddingsErrors];

export type GenerateEmbeddingsResponses = {
    /**
     * OK
     */
    200: EmbeddingResponseModel;
};

export type GenerateEmbeddingsResponse = GenerateEmbeddingsResponses[keyof GenerateEmbeddingsResponses];

export type GetAllProfilesData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        capability?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ai/management/api/v1/profiles';
};

export type GetAllProfilesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllProfilesResponses = {
    /**
     * OK
     */
    200: PagedProfileItemResponseModel;
};

export type GetAllProfilesResponse = GetAllProfilesResponses[keyof GetAllProfilesResponses];

export type CreateProfileData = {
    body?: CreateProfileRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/profiles';
};

export type CreateProfileErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type CreateProfileError = CreateProfileErrors[keyof CreateProfileErrors];

export type CreateProfileResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteProfileData = {
    body?: never;
    path: {
        profileIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/profiles/{profileIdOrAlias}';
};

export type DeleteProfileErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteProfileError = DeleteProfileErrors[keyof DeleteProfileErrors];

export type DeleteProfileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetProfileByIdOrAliasData = {
    body?: never;
    path: {
        profileIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/profiles/{profileIdOrAlias}';
};

export type GetProfileByIdOrAliasErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetProfileByIdOrAliasError = GetProfileByIdOrAliasErrors[keyof GetProfileByIdOrAliasErrors];

export type GetProfileByIdOrAliasResponses = {
    /**
     * OK
     */
    200: ProfileResponseModel;
};

export type GetProfileByIdOrAliasResponse = GetProfileByIdOrAliasResponses[keyof GetProfileByIdOrAliasResponses];

export type UpdateProfileData = {
    body?: UpdateProfileRequestModel;
    path: {
        profileIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/profiles/{profileIdOrAlias}';
};

export type UpdateProfileErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateProfileError = UpdateProfileErrors[keyof UpdateProfileErrors];

export type UpdateProfileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetAllProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/providers';
};

export type GetAllProvidersErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllProvidersResponses = {
    /**
     * OK
     */
    200: Array<ProviderItemResponseModel>;
};

export type GetAllProvidersResponse = GetAllProvidersResponses[keyof GetAllProvidersResponses];

export type GetProviderByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/providers/{id}';
};

export type GetProviderByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetProviderByIdError = GetProviderByIdErrors[keyof GetProviderByIdErrors];

export type GetProviderByIdResponses = {
    /**
     * OK
     */
    200: ProviderResponseModel;
};

export type GetProviderByIdResponse = GetProviderByIdResponses[keyof GetProviderByIdResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/settings';
};

export type GetSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: SettingsResponseModel;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type UpdateSettingsData = {
    body?: UpdateSettingsRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/settings';
};

export type UpdateSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type UpdateSettingsResponses = {
    /**
     * OK
     */
    200: SettingsResponseModel;
};

export type UpdateSettingsResponse = UpdateSettingsResponses[keyof UpdateSettingsResponses];

export type GetVersionHistoryData = {
    body?: never;
    path: {
        entityType: string;
        entityId: string;
    };
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ai/management/api/v1/versions/{entityType}/{entityId}';
};

export type GetVersionHistoryErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetVersionHistoryError = GetVersionHistoryErrors[keyof GetVersionHistoryErrors];

export type GetVersionHistoryResponses = {
    /**
     * OK
     */
    200: EntityVersionHistoryResponseModel;
};

export type GetVersionHistoryResponse = GetVersionHistoryResponses[keyof GetVersionHistoryResponses];

export type GetVersionData = {
    body?: never;
    path: {
        entityType: string;
        entityId: string;
        entityVersion: number;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/versions/{entityType}/{entityId}/{entityVersion}';
};

export type GetVersionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetVersionError = GetVersionErrors[keyof GetVersionErrors];

export type GetVersionResponses = {
    /**
     * OK
     */
    200: EntityVersionResponseModel;
};

export type GetVersionResponse = GetVersionResponses[keyof GetVersionResponses];

export type RollbackToVersionData = {
    body?: never;
    path: {
        entityType: string;
        entityId: string;
        entityVersion: number;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/versions/{entityType}/{entityId}/{entityVersion}/rollback';
};

export type RollbackToVersionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type RollbackToVersionError = RollbackToVersionErrors[keyof RollbackToVersionErrors];

export type RollbackToVersionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RollbackToVersionResponse = RollbackToVersionResponses[keyof RollbackToVersionResponses];

export type CompareVersionsData = {
    body?: never;
    path: {
        entityType: string;
        entityId: string;
        fromEntityVersion: number;
        toEntityVersion: number;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/versions/{entityType}/{entityId}/{fromEntityVersion}/compare/{toEntityVersion}';
};

export type CompareVersionsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type CompareVersionsError = CompareVersionsErrors[keyof CompareVersionsErrors];

export type CompareVersionsResponses = {
    /**
     * OK
     */
    200: EntityVersionComparisonResponseModel;
};

export type CompareVersionsResponse = CompareVersionsResponses[keyof CompareVersionsResponses];

export type GetSupportedEntityTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/versions/supported-types';
};

export type GetSupportedEntityTypesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetSupportedEntityTypesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetSupportedEntityTypesResponse = GetSupportedEntityTypesResponses[keyof GetSupportedEntityTypesResponses];
