// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost/' | (string & {});
};

export type AiDocumentMetadataModel = {
    contentTypeKey: string;
    variants: Array<AiVariantIdModel>;
    isVariant: boolean;
    isSegmented: boolean;
    name?: null | string;
};

export type AiPropertyOperationModel = 'AddItem' | 'RemoveItem' | 'MoveItem' | 'SetValue' | 'ClearValue';

export type AiPropertyValueOperationErrorModel = {
    code: string;
    message: string;
    details?: null | JsonObject;
};

export type AiVariantIdModel = {
    culture: null | string;
    segment: null | string;
    isInvariant: boolean;
};

export type AuditLogDetailResponseModel = {
    endTime?: null | string;
    entityType?: null | string;
    profileId: string;
    profileAlias: string;
    errorCategory?: null | string;
    totalTokens?: null | number;
    promptSnapshot?: null | string;
    responseSnapshot?: null | string;
    metadata?: null | Array<KeyValuePairOfstringAndstring>;
    id: string;
    startTime: string;
    durationMs?: null | number;
    status: string;
    userId: null | string;
    userName?: null | string;
    entityId?: null | string;
    capability: string;
    profileVersion: null | number;
    providerId: string;
    modelId: string;
    featureType?: null | string;
    featureId?: null | string;
    featureVersion?: null | number;
    parentAuditLogId?: null | string;
    inputTokens?: null | number;
    outputTokens?: null | number;
    errorMessage?: null | string;
};

export type AuditLogItemResponseModel = {
    id: string;
    startTime: string;
    durationMs?: null | number;
    status: string;
    userId: null | string;
    userName?: null | string;
    entityId?: null | string;
    capability: string;
    profileId: string;
    profileAlias: string;
    profileVersion: null | number;
    providerId: string;
    modelId: string;
    featureType?: null | string;
    featureId?: null | string;
    featureVersion?: null | number;
    parentAuditLogId?: null | string;
    inputTokens?: null | number;
    outputTokens?: null | number;
    errorMessage?: null | string;
};

export type BinaryChatContentPartModel = {
    $type: 'binary';
    mimeType: string;
    data: string;
    filename?: null | string;
};

export type ChatContentPartModel = ({
    $type?: 'text';
} & TextChatContentPartModel) | ({
    $type?: 'binary';
} & BinaryChatContentPartModel);

export type ChatMessageModel = {
    role: string;
    content?: null | string;
    contentParts?: null | Array<ChatContentPartModel>;
};

export type ChatProfileSettingsModel = {
    $type: 'chat';
    temperature?: null | number;
    maxTokens?: null | number;
    systemPromptTemplate?: null | string;
    contextIds: Array<string>;
    guardrailIds: Array<string>;
};

export type ChatRequestModel = {
    messages: Array<ChatMessageModel>;
};

export type ChatResponseModel = {
    message: ChatMessageModel;
    finishReason?: null | string;
    usage?: null | UsageModel;
};

export type CompareRunsRequestModel = {
    baselineTestRunId: string;
    comparisonTestRunId: string;
};

export type CompareVariationsRequestModel = {
    executionId: string;
    sourceVariationId?: null | string;
    comparisonVariationId: string;
};

export type ConnectionItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    providerId: string;
    isActive: boolean;
    dateCreated: string;
    dateModified: string;
    version: number;
};

export type ConnectionResponseModel = {
    id: string;
    alias: string;
    name: string;
    providerId: string;
    settings?: unknown;
    isActive: boolean;
    dateCreated: string;
    dateModified: string;
    version: number;
};

export type ConnectionTestResultModel = {
    success: boolean;
    errorMessage?: null | string;
};

export type ContextItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    resourceCount: number;
    dateCreated: string;
    dateModified: string;
};

export type ContextResourceModel = {
    id: string;
    resourceTypeId: string;
    name: string;
    description?: null | string;
    sortOrder: number;
    settings?: unknown;
    injectionMode: string;
};

export type ContextResourceTypeResponseModel = {
    id: string;
    name: string;
    description?: null | string;
    icon?: null | string;
    settingsSchema?: null | EditableModelSchemaModel;
};

export type ContextResponseModel = {
    id: string;
    alias: string;
    name: string;
    dateCreated: string;
    dateModified: string;
    resources: Array<ContextResourceModel>;
    version: number;
};

export type CreateConnectionRequestModel = {
    alias: string;
    name: string;
    providerId: string;
    settings?: unknown;
    isActive: boolean;
};

export type CreateContextRequestModel = {
    alias: string;
    name: string;
    resources: Array<ContextResourceModel>;
};

export type CreateGuardrailRequestModel = {
    alias: string;
    name: string;
    rules: Array<GuardrailRuleModel>;
};

export type CreateProfileRequestModel = {
    alias: string;
    name: string;
    capability: string;
    model: ModelRefModel;
    connectionId: string;
    settings?: null | ProfileSettingsModel;
    capabilitySettings?: unknown;
    tags: Array<string>;
};

export type CreateTestRequestModel = {
    alias: string;
    name: string;
    description?: null | string;
    testFeatureId: string;
    testTargetId: string;
    profileId?: null | string;
    contextIds?: null | Array<string>;
    testFeatureConfig?: null | JsonElement;
    graders: Array<TestGraderModel>;
    variations?: null | Array<TestVariationModel>;
    runCount: number;
    tags: Array<string>;
};

export type EditableModelFieldModel = {
    key: string;
    label: string;
    description?: null | string;
    editorUiAlias?: null | string;
    editorConfig?: unknown;
    defaultValue?: unknown;
    sortOrder: number;
    isRequired: boolean;
    group?: null | string;
};

export type EditableModelSchemaModel = {
    type?: null | Type;
    fields: Array<EditableModelFieldModel>;
};

export type EmbeddingItemModel = {
    index: number;
    vector: Array<number>;
};

export type EmbeddingProfileSettingsModel = {
    $type: 'embedding';
    dimensions?: null | number;
};

export type EmbeddingResponseModel = {
    embeddings: Array<EmbeddingItemModel>;
};

export type EntityVersionComparisonResponseModel = {
    fromVersion: number;
    toVersion: number;
    changes: Array<ValueChangeModel>;
};

export type EntityVersionHistoryResponseModel = {
    currentVersion: number;
    totalVersions: number;
    versions: Array<EntityVersionResponseModel>;
};

export type EntityVersionResponseModel = {
    id: string;
    entityId: string;
    version: number;
    dateCreated: string;
    createdByUserId?: null | string;
    createdByUserName?: null | string;
    changeDescription?: null | string;
};

export type GeneratedImageModel = {
    data?: null | string;
    url?: null | string;
    mediaType?: null | string;
};

export type GenerateEmbeddingRequestModel = {
    profileIdOrAlias?: null | IdOrAliasModel;
    values: Array<string>;
};

export type GenerateImageRequestModel = {
    prompt: string;
    profileIdOrAlias?: null | string;
    count?: null | number;
    size?: null | string;
    responseFormat?: null | string;
    originalImages?: null | Array<ImageInputModel>;
};

export type GenerateImageResponseModel = {
    images: Array<GeneratedImageModel>;
    usage?: null | ImageGenerationUsageModel;
};

export type GuardrailEvaluatorInfoModel = {
    id: string;
    name: string;
    description?: null | string;
    type: string;
    supportsRedaction: boolean;
    configSchema?: null | EditableModelSchemaModel;
};

export type GuardrailItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    ruleCount: number;
    dateCreated: string;
    dateModified: string;
};

export type GuardrailResponseModel = {
    id: string;
    alias: string;
    name: string;
    dateCreated: string;
    dateModified: string;
    rules: Array<GuardrailRuleModel>;
    version: number;
};

export type GuardrailRuleModel = {
    id: string;
    evaluatorId: string;
    name: string;
    phase: string;
    action: string;
    config?: null | JsonElement;
    sortOrder: number;
};

export type IdOrAliasModel = string;

export type IFormFile = Blob | File;

export type ImageGenerationProfileSettingsModel = {
    $type: 'imageGeneration';
    size?: null | string;
    quality?: null | string;
    style?: null | string;
    mediaType?: null | string;
};

export type ImageGenerationUsageModel = {
    inputTokens?: null | number;
    outputTokens?: null | number;
    totalTokens?: null | number;
};

export type ImageInputModel = {
    data: string;
    mediaType: string;
};

export type JsonElement = unknown;

export type JsonNode = unknown;

export type JsonObject = {
    [key: string]: unknown;
};

export type KeyValuePairOfstringAndstring = {
    key: null | string;
    value: null | string;
};

export type KnowledgeSetDetailResponseModel = {
    id: string;
    name: string;
    description?: null | string;
    icon?: null | string;
    items: Array<KnowledgeSetItemModel>;
};

export type KnowledgeSetItemContentResponseModel = {
    key: string;
    content: string;
};

export type KnowledgeSetItemModel = {
    key: string;
    name: string;
    description?: null | string;
};

export type KnowledgeSetResponseModel = {
    id: string;
    name: string;
    description?: null | string;
    icon?: null | string;
    itemCount: number;
};

export type ModelDescriptorResponseModel = {
    model: null | ModelRefModel;
    name: string;
    metadata?: null | {
        [key: string]: string;
    };
};

export type ModelRefModel = {
    providerId: string;
    modelId: string;
};

export type PagedAuditLogItemResponseModel = {
    total: number;
    items: Array<AuditLogItemResponseModel>;
};

export type PagedConnectionItemResponseModel = {
    total: number;
    items: Array<ConnectionItemResponseModel>;
};

export type PagedContextItemResponseModel = {
    total: number;
    items: Array<ContextItemResponseModel>;
};

export type PagedGuardrailItemResponseModel = {
    total: number;
    items: Array<GuardrailItemResponseModel>;
};

export type PagedModelTestRunResponseModel = {
    items: Array<TestRunResponseModel>;
    total: number;
};

export type PagedProfileItemResponseModel = {
    total: number;
    items: Array<ProfileItemResponseModel>;
};

export type PagedTestItemResponseModel = {
    total: number;
    items: Array<TestItemResponseModel>;
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number;
    detail?: null | string;
    instance?: null | string;
};

export type ProfileItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    capability: string;
    model?: null | ModelRefModel;
    dateCreated: string;
    dateModified: string;
};

export type ProfileResponseModel = {
    id: string;
    alias: string;
    name: string;
    capability: string;
    model?: null | ModelRefModel;
    connectionId: string;
    settings?: null | ProfileSettingsModel;
    capabilitySettings?: unknown;
    tags: Array<string>;
    dateCreated: string;
    dateModified: string;
    version: number;
};

export type ProfileSettingsModel = ({
    $type?: 'chat';
} & ChatProfileSettingsModel) | ({
    $type?: 'embedding';
} & EmbeddingProfileSettingsModel) | ({
    $type?: 'speechToText';
} & SpeechToTextProfileSettingsModel) | ({
    $type?: 'imageGeneration';
} & ImageGenerationProfileSettingsModel);

export type PropertyValueOperationRequestModel = {
    path: Array<unknown>;
    operation: AiPropertyOperationModel;
    args?: null | JsonNode;
    rootValue?: null | JsonNode;
    documentMetadata: AiDocumentMetadataModel;
};

export type PropertyValueOperationResponseModel = {
    success: boolean;
    newRootValue?: null | JsonNode;
    blockKey?: null | string;
    error?: null | AiPropertyValueOperationErrorModel;
};

export type ProviderItemResponseModel = {
    id: string;
    name: string;
    capabilities: Array<string>;
};

export type ProviderResponseModel = {
    id: string;
    name: string;
    capabilities: Array<string>;
    settingsSchema?: null | EditableModelSchemaModel;
    capabilitySettingsSchemas: {
        [key: string]: EditableModelSchemaModel;
    };
};

export type RunTestBatchRequestModel = {
    testIds: Array<string>;
    profileIdOverride?: null | string;
    contextIdsOverride?: null | Array<string>;
    guardrailIdsOverride?: null | Array<string>;
};

export type RunTestRequestModel = {
    profileIdOverride?: null | string;
    contextIdsOverride?: null | Array<string>;
    guardrailIdsOverride?: null | Array<string>;
};

export type RunTestsByTagsRequestModel = {
    tags: Array<string>;
    profileIdOverride?: null | string;
    contextIdsOverride?: null | Array<string>;
    guardrailIdsOverride?: null | Array<string>;
};

export type SettingsResponseModel = {
    defaultChatProfileId?: null | string;
    defaultEmbeddingProfileId?: null | string;
    classifierChatProfileId?: null | string;
    defaultSpeechToTextProfileId?: null | string;
    defaultImageGenerationProfileId?: null | string;
};

export type SpeechToTextProfileSettingsModel = {
    $type: 'speechToText';
    language?: null | string;
};

export type SpeechToTextResponseModel = {
    text: string;
};

export type TestBatchResultsResponseModel = {
    results: {
        [key: string]: TestExecutionResultResponseModel;
    };
};

export type TestEntitySubTypeResponseModel = {
    alias: string;
    name: string;
    icon?: null | string;
    description?: null | string;
    unique?: null | string;
};

export type TestEntityTypeResponseModel = {
    entityType: string;
    name: string;
    icon?: null | string;
    hasSubTypes: boolean;
};

export type TestExecutionResultResponseModel = {
    testId: string;
    executionId: string;
    batchId?: null | string;
    defaultMetrics: TestMetricsResponseModel;
    variationMetrics: Array<TestVariationMetricsResponseModel>;
    aggregateMetrics: TestMetricsResponseModel;
};

export type TestFeatureInfoModel = {
    id: string;
    name: string;
    description?: null | string;
    category?: null | string;
};

export type TestFeatureResponseModel = {
    id: string;
    name: string;
    description?: null | string;
    category?: null | string;
    testFeatureConfigSchema?: null | EditableModelSchemaModel;
};

export type TestGraderComparisonResponseModel = {
    graderId: string;
    graderName: string;
    baselineResult?: null | TestGraderResultResponseModel;
    comparisonResult?: null | TestGraderResultResponseModel;
    changed: boolean;
    scoreChange: number;
};

export type TestGraderInfoModel = {
    id: string;
    name: string;
    description?: null | string;
    type: string;
};

export type TestGraderModel = {
    id: string;
    graderTypeId: string;
    name: string;
    description?: null | string;
    config?: null | JsonElement;
    negate: boolean;
    severity: string;
    weight: number;
};

export type TestGraderResponseModel = {
    id: string;
    name: string;
    description?: null | string;
    type: string;
    configSchema?: null | EditableModelSchemaModel;
};

export type TestGraderResultResponseModel = {
    graderId: string;
    graderName?: null | string;
    graderTypeId?: null | string;
    graderType?: null | string;
    weight: number;
    negate: boolean;
    passed: boolean;
    score: number;
    actualValue?: null | string;
    expectedValue?: null | string;
    failureMessage?: null | string;
    metadata?: null | JsonElement;
    severity: string;
};

export type TestItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    description?: null | string;
    testFeatureId: string;
    tags: Array<string>;
    runCount: number;
    dateCreated: string;
    dateModified: string;
    version: number;
};

export type TestMetricsResponseModel = {
    testId: string;
    totalRuns: number;
    passedRuns: number;
    passAtK: number;
    passToTheK: number;
    runIds: Array<string>;
};

export type TestOutcomeResponseModel = {
    outputType: string;
    outputValue?: null | string;
    finishReason?: null | string;
    tokenUsage?: null | TestTokenUsageResponseModel;
};

export type TestResponseModel = {
    id: string;
    alias: string;
    name: string;
    description?: null | string;
    testFeatureId: string;
    testTargetId: string;
    profileId?: null | string;
    contextIds: Array<string>;
    testFeatureConfig?: null | JsonElement;
    graders: Array<TestGraderModel>;
    variations: Array<TestVariationModel>;
    runCount: number;
    tags: Array<string>;
    dateCreated: string;
    dateModified: string;
    baselineRunId?: null | string;
    version: number;
};

export type TestRunComparisonResponseModel = {
    baselineRun: TestRunResponseModel;
    comparisonRun: TestRunResponseModel;
    isRegression: boolean;
    isImprovement: boolean;
    durationChangeMs: number;
    graderComparisons: Array<TestGraderComparisonResponseModel>;
};

export type TestRunErrorResponseModel = {
    message: string;
    stackTrace?: null | string;
};

export type TestRunResponseModel = {
    id: string;
    testId: string;
    testName?: null | string;
    testVersion: number;
    runNumber: number;
    profileId?: null | string;
    contextIds: Array<string>;
    executedAt: string;
    executedByUserId?: null | string;
    status: string;
    durationMs: number;
    transcriptId?: null | string;
    outcome?: null | TestOutcomeResponseModel;
    graderResults: Array<TestGraderResultResponseModel>;
    error?: null | TestRunErrorResponseModel;
    batchId?: null | string;
    isBaseline: boolean;
    baselineRunId?: null | string;
    executionId: string;
    variationId?: null | string;
    variationName?: null | string;
};

export type TestTokenUsageResponseModel = {
    inputTokens: number;
    outputTokens: number;
    totalTokens: number;
};

export type TestTranscriptResponseModel = {
    id: string;
    messages?: null | JsonElement;
    toolCalls?: null | JsonElement;
    reasoning?: null | JsonElement;
    timing?: null | JsonElement;
    finalOutput?: null | JsonElement;
};

export type TestVariationComparisonResponseModel = {
    sourceVariationName: string;
    sourceMetrics: TestMetricsResponseModel;
    comparisonVariationName: string;
    comparisonMetrics: TestMetricsResponseModel;
    passRateDelta: number;
    averageDurationDeltaMs: number;
    isRegression: boolean;
    isImprovement: boolean;
};

export type TestVariationMetricsResponseModel = {
    variationId: string;
    variationName: string;
    metrics: TestMetricsResponseModel;
};

export type TestVariationModel = {
    id: string;
    name: string;
    description?: null | string;
    profileId?: null | string;
    runCount?: null | number;
    contextIds?: null | Array<string>;
    testFeatureConfig?: null | JsonElement;
};

export type TextChatContentPartModel = {
    $type: 'text';
    text: string;
};

export type ToolItemResponseModel = {
    id: string;
    name: string;
    description: string;
    scopeId: string;
    isDestructive: boolean;
    tags: Array<string>;
};

export type ToolScopeItemResponseModel = {
    id: string;
    icon: string;
    isDestructive: boolean;
    domain: string;
};

export type Type = string;

export type UpdateConnectionRequestModel = {
    alias: string;
    name: string;
    settings?: unknown;
    isActive: boolean;
};

export type UpdateContextRequestModel = {
    alias: string;
    name: string;
    resources: Array<ContextResourceModel>;
};

export type UpdateGuardrailRequestModel = {
    alias: string;
    name: string;
    rules: Array<GuardrailRuleModel>;
};

export type UpdateProfileRequestModel = {
    alias: string;
    name: string;
    model: ModelRefModel;
    connectionId: string;
    settings?: null | ProfileSettingsModel;
    capabilitySettings?: unknown;
    tags: Array<string>;
};

export type UpdateSettingsRequestModel = {
    defaultChatProfileId?: null | string;
    defaultEmbeddingProfileId?: null | string;
    classifierChatProfileId?: null | string;
    defaultSpeechToTextProfileId?: null | string;
    defaultImageGenerationProfileId?: null | string;
};

export type UpdateTestRequestModel = {
    alias: string;
    name: string;
    description?: null | string;
    testTargetId: string;
    profileId?: null | string;
    contextIds?: null | Array<string>;
    testFeatureConfig?: null | JsonElement;
    graders: Array<TestGraderModel>;
    variations?: null | Array<TestVariationModel>;
    runCount: number;
    tags: Array<string>;
};

export type UsageBreakdownItemModel = {
    dimension: string;
    dimensionName?: null | string;
    requestCount: number;
    totalTokens: number;
    percentage: number;
};

export type UsageModel = {
    inputTokens?: null | number;
    outputTokens?: null | number;
    totalTokens?: null | number;
};

export type UsageSummaryResponseModel = {
    totalRequests: number;
    inputTokens: number;
    outputTokens: number;
    totalTokens: number;
    successCount: number;
    failureCount: number;
    successRate: number;
    averageDurationMs: number;
};

export type UsageTimeSeriesPointModel = {
    timestamp: string;
    requestCount: number;
    totalTokens: number;
    inputTokens: number;
    outputTokens: number;
    successCount: number;
    failureCount: number;
};

export type ValueChangeModel = {
    path: string;
    oldValue?: null | string;
    newValue?: null | string;
};

export type GetUsageBreakdownByModelData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
        granularity?: string;
    };
    url: '/umbraco/ai/management/api/v1/analytics/usage-by-model';
};

export type GetUsageBreakdownByModelErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUsageBreakdownByModelResponses = {
    /**
     * OK
     */
    200: Array<UsageBreakdownItemModel>;
};

export type GetUsageBreakdownByModelResponse = GetUsageBreakdownByModelResponses[keyof GetUsageBreakdownByModelResponses];

export type GetUsageBreakdownByProfileData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
        granularity?: string;
    };
    url: '/umbraco/ai/management/api/v1/analytics/usage-by-profile';
};

export type GetUsageBreakdownByProfileErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUsageBreakdownByProfileResponses = {
    /**
     * OK
     */
    200: Array<UsageBreakdownItemModel>;
};

export type GetUsageBreakdownByProfileResponse = GetUsageBreakdownByProfileResponses[keyof GetUsageBreakdownByProfileResponses];

export type GetUsageBreakdownByProviderData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
        granularity?: string;
    };
    url: '/umbraco/ai/management/api/v1/analytics/usage-by-provider';
};

export type GetUsageBreakdownByProviderErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUsageBreakdownByProviderResponses = {
    /**
     * OK
     */
    200: Array<UsageBreakdownItemModel>;
};

export type GetUsageBreakdownByProviderResponse = GetUsageBreakdownByProviderResponses[keyof GetUsageBreakdownByProviderResponses];

export type GetUsageBreakdownByUserData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
        granularity?: string;
    };
    url: '/umbraco/ai/management/api/v1/analytics/usage-by-user';
};

export type GetUsageBreakdownByUserErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUsageBreakdownByUserResponses = {
    /**
     * OK
     */
    200: Array<UsageBreakdownItemModel>;
};

export type GetUsageBreakdownByUserResponse = GetUsageBreakdownByUserResponses[keyof GetUsageBreakdownByUserResponses];

export type GetUsageSummaryData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
        granularity?: string;
    };
    url: '/umbraco/ai/management/api/v1/analytics/usage-summary';
};

export type GetUsageSummaryErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUsageSummaryResponses = {
    /**
     * OK
     */
    200: UsageSummaryResponseModel;
};

export type GetUsageSummaryResponse = GetUsageSummaryResponses[keyof GetUsageSummaryResponses];

export type GetUsageTimeSeriesData = {
    body?: never;
    path?: never;
    query?: {
        from?: string;
        to?: string;
        granularity?: string;
    };
    url: '/umbraco/ai/management/api/v1/analytics/usage-time-series';
};

export type GetUsageTimeSeriesErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUsageTimeSeriesResponses = {
    /**
     * OK
     */
    200: Array<UsageTimeSeriesPointModel>;
};

export type GetUsageTimeSeriesResponse = GetUsageTimeSeriesResponses[keyof GetUsageTimeSeriesResponses];

export type GetAuditLogsData = {
    body?: never;
    path?: never;
    query?: {
        status?: string;
        userId?: string;
        profileId?: string;
        providerId?: string;
        entityId?: string;
        fromDate?: string;
        toDate?: string;
        searchText?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ai/management/api/v1/audit-logs';
};

export type GetAuditLogsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAuditLogsResponses = {
    /**
     * OK
     */
    200: PagedAuditLogItemResponseModel;
};

export type GetAuditLogsResponse = GetAuditLogsResponses[keyof GetAuditLogsResponses];

export type DeleteAuditLogData = {
    body?: never;
    path: {
        auditLogId: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/audit-logs/{auditLogId}';
};

export type DeleteAuditLogErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteAuditLogError = DeleteAuditLogErrors[keyof DeleteAuditLogErrors];

export type DeleteAuditLogResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetAuditLogByIdentifierData = {
    body?: never;
    path: {
        auditLogId: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/audit-logs/{auditLogId}';
};

export type GetAuditLogByIdentifierErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetAuditLogByIdentifierError = GetAuditLogByIdentifierErrors[keyof GetAuditLogByIdentifierErrors];

export type GetAuditLogByIdentifierResponses = {
    /**
     * OK
     */
    200: AuditLogDetailResponseModel;
};

export type GetAuditLogByIdentifierResponse = GetAuditLogByIdentifierResponses[keyof GetAuditLogByIdentifierResponses];

export type CleanupAuditLogsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/audit-logs/cleanup';
};

export type CleanupAuditLogsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CleanupAuditLogsResponses = {
    /**
     * OK
     */
    200: number;
};

export type CleanupAuditLogsResponse = CleanupAuditLogsResponses[keyof CleanupAuditLogsResponses];

export type CompleteChatData = {
    body: ChatRequestModel;
    headers?: {
        profileIdOrAlias?: string;
    };
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/chat/complete';
};

export type CompleteChatErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
    /**
     * Unprocessable Entity
     */
    422: ProblemDetails;
};

export type CompleteChatError = CompleteChatErrors[keyof CompleteChatErrors];

export type CompleteChatResponses = {
    /**
     * OK
     */
    200: ChatResponseModel;
};

export type CompleteChatResponse = CompleteChatResponses[keyof CompleteChatResponses];

export type GetAllConnectionsData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        providerId?: string;
        capability?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ai/management/api/v1/connections';
};

export type GetAllConnectionsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllConnectionsResponses = {
    /**
     * OK
     */
    200: PagedConnectionItemResponseModel;
};

export type GetAllConnectionsResponse = GetAllConnectionsResponses[keyof GetAllConnectionsResponses];

export type CreateConnectionData = {
    body: CreateConnectionRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections';
};

export type CreateConnectionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type CreateConnectionError = CreateConnectionErrors[keyof CreateConnectionErrors];

export type CreateConnectionResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type ConnectionAliasExistsData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: {
        excludeId?: string;
    };
    url: '/umbraco/ai/management/api/v1/connections/{alias}/exists';
};

export type ConnectionAliasExistsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ConnectionAliasExistsResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type ConnectionAliasExistsResponse = ConnectionAliasExistsResponses[keyof ConnectionAliasExistsResponses];

export type DeleteConnectionData = {
    body?: never;
    path: {
        connectionIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/{connectionIdOrAlias}';
};

export type DeleteConnectionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteConnectionError = DeleteConnectionErrors[keyof DeleteConnectionErrors];

export type DeleteConnectionResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetConnectionByIdOrAliasData = {
    body?: never;
    path: {
        connectionIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/{connectionIdOrAlias}';
};

export type GetConnectionByIdOrAliasErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetConnectionByIdOrAliasError = GetConnectionByIdOrAliasErrors[keyof GetConnectionByIdOrAliasErrors];

export type GetConnectionByIdOrAliasResponses = {
    /**
     * OK
     */
    200: ConnectionResponseModel;
};

export type GetConnectionByIdOrAliasResponse = GetConnectionByIdOrAliasResponses[keyof GetConnectionByIdOrAliasResponses];

export type UpdateConnectionData = {
    body: UpdateConnectionRequestModel;
    path: {
        connectionIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/{connectionIdOrAlias}';
};

export type UpdateConnectionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateConnectionError = UpdateConnectionErrors[keyof UpdateConnectionErrors];

export type UpdateConnectionResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetCapabilitiesData = {
    body?: never;
    path: {
        connectionIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/{connectionIdOrAlias}/capabilities';
};

export type GetCapabilitiesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetCapabilitiesError = GetCapabilitiesErrors[keyof GetCapabilitiesErrors];

export type GetCapabilitiesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetCapabilitiesResponse = GetCapabilitiesResponses[keyof GetCapabilitiesResponses];

export type GetModelsData = {
    body?: never;
    path: {
        connectionIdOrAlias: string;
    };
    query?: {
        capability?: string;
    };
    url: '/umbraco/ai/management/api/v1/connections/{connectionIdOrAlias}/models';
};

export type GetModelsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetModelsError = GetModelsErrors[keyof GetModelsErrors];

export type GetModelsResponses = {
    /**
     * OK
     */
    200: Array<ModelDescriptorResponseModel>;
};

export type GetModelsResponse = GetModelsResponses[keyof GetModelsResponses];

export type TestConnectionData = {
    body?: never;
    path: {
        connectionIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/{connectionIdOrAlias}/test';
};

export type TestConnectionErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type TestConnectionError = TestConnectionErrors[keyof TestConnectionErrors];

export type TestConnectionResponses = {
    /**
     * OK
     */
    200: ConnectionTestResultModel;
};

export type TestConnectionResponse = TestConnectionResponses[keyof TestConnectionResponses];

export type GetAllCapabilitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/connections/capabilities';
};

export type GetAllCapabilitiesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllCapabilitiesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetAllCapabilitiesResponse = GetAllCapabilitiesResponses[keyof GetAllCapabilitiesResponses];

export type GetAllContextResourceTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/context-resource-types';
};

export type GetAllContextResourceTypesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllContextResourceTypesResponses = {
    /**
     * OK
     */
    200: Array<ContextResourceTypeResponseModel>;
};

export type GetAllContextResourceTypesResponse = GetAllContextResourceTypesResponses[keyof GetAllContextResourceTypesResponses];

export type GetContextResourceTypeByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/context-resource-types/{id}';
};

export type GetContextResourceTypeByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetContextResourceTypeByIdError = GetContextResourceTypeByIdErrors[keyof GetContextResourceTypeByIdErrors];

export type GetContextResourceTypeByIdResponses = {
    /**
     * OK
     */
    200: ContextResourceTypeResponseModel;
};

export type GetContextResourceTypeByIdResponse = GetContextResourceTypeByIdResponses[keyof GetContextResourceTypeByIdResponses];

export type GetAllContextsData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ai/management/api/v1/contexts';
};

export type GetAllContextsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllContextsResponses = {
    /**
     * OK
     */
    200: PagedContextItemResponseModel;
};

export type GetAllContextsResponse = GetAllContextsResponses[keyof GetAllContextsResponses];

export type CreateContextData = {
    body: CreateContextRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/contexts';
};

export type CreateContextErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CreateContextError = CreateContextErrors[keyof CreateContextErrors];

export type CreateContextResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type ContextAliasExistsData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: {
        excludeId?: string;
    };
    url: '/umbraco/ai/management/api/v1/contexts/{alias}/exists';
};

export type ContextAliasExistsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ContextAliasExistsResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type ContextAliasExistsResponse = ContextAliasExistsResponses[keyof ContextAliasExistsResponses];

export type DeleteContextData = {
    body?: never;
    path: {
        contextIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/contexts/{contextIdOrAlias}';
};

export type DeleteContextErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteContextError = DeleteContextErrors[keyof DeleteContextErrors];

export type DeleteContextResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetContextByIdOrAliasData = {
    body?: never;
    path: {
        contextIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/contexts/{contextIdOrAlias}';
};

export type GetContextByIdOrAliasErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetContextByIdOrAliasError = GetContextByIdOrAliasErrors[keyof GetContextByIdOrAliasErrors];

export type GetContextByIdOrAliasResponses = {
    /**
     * OK
     */
    200: ContextResponseModel;
};

export type GetContextByIdOrAliasResponse = GetContextByIdOrAliasResponses[keyof GetContextByIdOrAliasResponses];

export type UpdateContextData = {
    body: UpdateContextRequestModel;
    path: {
        contextIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/contexts/{contextIdOrAlias}';
};

export type UpdateContextErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateContextError = UpdateContextErrors[keyof UpdateContextErrors];

export type UpdateContextResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GenerateEmbeddingsData = {
    body: GenerateEmbeddingRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/embeddings/generate';
};

export type GenerateEmbeddingsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GenerateEmbeddingsError = GenerateEmbeddingsErrors[keyof GenerateEmbeddingsErrors];

export type GenerateEmbeddingsResponses = {
    /**
     * OK
     */
    200: EmbeddingResponseModel;
};

export type GenerateEmbeddingsResponse = GenerateEmbeddingsResponses[keyof GenerateEmbeddingsResponses];

export type GetAllGuardrailEvaluatorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/guardrail-evaluators';
};

export type GetAllGuardrailEvaluatorsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllGuardrailEvaluatorsResponses = {
    /**
     * OK
     */
    200: Array<GuardrailEvaluatorInfoModel>;
};

export type GetAllGuardrailEvaluatorsResponse = GetAllGuardrailEvaluatorsResponses[keyof GetAllGuardrailEvaluatorsResponses];

export type GetAllGuardrailsData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ai/management/api/v1/guardrails';
};

export type GetAllGuardrailsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllGuardrailsResponses = {
    /**
     * OK
     */
    200: PagedGuardrailItemResponseModel;
};

export type GetAllGuardrailsResponse = GetAllGuardrailsResponses[keyof GetAllGuardrailsResponses];

export type CreateGuardrailData = {
    body: CreateGuardrailRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/guardrails';
};

export type CreateGuardrailErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CreateGuardrailError = CreateGuardrailErrors[keyof CreateGuardrailErrors];

export type CreateGuardrailResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type GuardrailAliasExistsData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: {
        excludeId?: string;
    };
    url: '/umbraco/ai/management/api/v1/guardrails/{alias}/exists';
};

export type GuardrailAliasExistsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GuardrailAliasExistsResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type GuardrailAliasExistsResponse = GuardrailAliasExistsResponses[keyof GuardrailAliasExistsResponses];

export type DeleteGuardrailData = {
    body?: never;
    path: {
        guardrailIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/guardrails/{guardrailIdOrAlias}';
};

export type DeleteGuardrailErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteGuardrailError = DeleteGuardrailErrors[keyof DeleteGuardrailErrors];

export type DeleteGuardrailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetGuardrailByIdOrAliasData = {
    body?: never;
    path: {
        guardrailIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/guardrails/{guardrailIdOrAlias}';
};

export type GetGuardrailByIdOrAliasErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetGuardrailByIdOrAliasError = GetGuardrailByIdOrAliasErrors[keyof GetGuardrailByIdOrAliasErrors];

export type GetGuardrailByIdOrAliasResponses = {
    /**
     * OK
     */
    200: GuardrailResponseModel;
};

export type GetGuardrailByIdOrAliasResponse = GetGuardrailByIdOrAliasResponses[keyof GetGuardrailByIdOrAliasResponses];

export type UpdateGuardrailData = {
    body: UpdateGuardrailRequestModel;
    path: {
        guardrailIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/guardrails/{guardrailIdOrAlias}';
};

export type UpdateGuardrailErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateGuardrailError = UpdateGuardrailErrors[keyof UpdateGuardrailErrors];

export type UpdateGuardrailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GenerateData = {
    body: GenerateImageRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/image-generation/generate';
};

export type GenerateErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GenerateError = GenerateErrors[keyof GenerateErrors];

export type GenerateResponses = {
    /**
     * OK
     */
    200: GenerateImageResponseModel;
};

export type GenerateResponse = GenerateResponses[keyof GenerateResponses];

export type GetAllKnowledgeSetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/knowledge-sets';
};

export type GetAllKnowledgeSetsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllKnowledgeSetsResponses = {
    /**
     * OK
     */
    200: Array<KnowledgeSetResponseModel>;
};

export type GetAllKnowledgeSetsResponse = GetAllKnowledgeSetsResponses[keyof GetAllKnowledgeSetsResponses];

export type GetKnowledgeSetByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/knowledge-sets/{id}';
};

export type GetKnowledgeSetByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetKnowledgeSetByIdError = GetKnowledgeSetByIdErrors[keyof GetKnowledgeSetByIdErrors];

export type GetKnowledgeSetByIdResponses = {
    /**
     * OK
     */
    200: KnowledgeSetDetailResponseModel;
};

export type GetKnowledgeSetByIdResponse = GetKnowledgeSetByIdResponses[keyof GetKnowledgeSetByIdResponses];

export type GetKnowledgeSetItemContentData = {
    body?: never;
    path: {
        id: string;
        key: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/knowledge-sets/{id}/item/{key}';
};

export type GetKnowledgeSetItemContentErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetKnowledgeSetItemContentError = GetKnowledgeSetItemContentErrors[keyof GetKnowledgeSetItemContentErrors];

export type GetKnowledgeSetItemContentResponses = {
    /**
     * OK
     */
    200: KnowledgeSetItemContentResponseModel;
};

export type GetKnowledgeSetItemContentResponse = GetKnowledgeSetItemContentResponses[keyof GetKnowledgeSetItemContentResponses];

export type GetAllProfilesData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        capability?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ai/management/api/v1/profiles';
};

export type GetAllProfilesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllProfilesResponses = {
    /**
     * OK
     */
    200: PagedProfileItemResponseModel;
};

export type GetAllProfilesResponse = GetAllProfilesResponses[keyof GetAllProfilesResponses];

export type CreateProfileData = {
    body: CreateProfileRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/profiles';
};

export type CreateProfileErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type CreateProfileError = CreateProfileErrors[keyof CreateProfileErrors];

export type CreateProfileResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type ProfileAliasExistsData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: {
        excludeId?: string;
    };
    url: '/umbraco/ai/management/api/v1/profiles/{alias}/exists';
};

export type ProfileAliasExistsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ProfileAliasExistsResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type ProfileAliasExistsResponse = ProfileAliasExistsResponses[keyof ProfileAliasExistsResponses];

export type DeleteProfileData = {
    body?: never;
    path: {
        profileIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/profiles/{profileIdOrAlias}';
};

export type DeleteProfileErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteProfileError = DeleteProfileErrors[keyof DeleteProfileErrors];

export type DeleteProfileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetProfileByIdOrAliasData = {
    body?: never;
    path: {
        profileIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/profiles/{profileIdOrAlias}';
};

export type GetProfileByIdOrAliasErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetProfileByIdOrAliasError = GetProfileByIdOrAliasErrors[keyof GetProfileByIdOrAliasErrors];

export type GetProfileByIdOrAliasResponses = {
    /**
     * OK
     */
    200: ProfileResponseModel;
};

export type GetProfileByIdOrAliasResponse = GetProfileByIdOrAliasResponses[keyof GetProfileByIdOrAliasResponses];

export type UpdateProfileData = {
    body: UpdateProfileRequestModel;
    path: {
        profileIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/profiles/{profileIdOrAlias}';
};

export type UpdateProfileErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateProfileError = UpdateProfileErrors[keyof UpdateProfileErrors];

export type UpdateProfileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type InvokeData = {
    body: PropertyValueOperationRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/property-value-operation';
};

export type InvokeErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type InvokeResponses = {
    /**
     * OK
     */
    200: PropertyValueOperationResponseModel;
};

export type InvokeResponse = InvokeResponses[keyof InvokeResponses];

export type GetAllProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/providers';
};

export type GetAllProvidersErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllProvidersResponses = {
    /**
     * OK
     */
    200: Array<ProviderItemResponseModel>;
};

export type GetAllProvidersResponse = GetAllProvidersResponses[keyof GetAllProvidersResponses];

export type GetProviderByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/providers/{id}';
};

export type GetProviderByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetProviderByIdError = GetProviderByIdErrors[keyof GetProviderByIdErrors];

export type GetProviderByIdResponses = {
    /**
     * OK
     */
    200: ProviderResponseModel;
};

export type GetProviderByIdResponse = GetProviderByIdResponses[keyof GetProviderByIdResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/settings';
};

export type GetSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: SettingsResponseModel;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type UpdateSettingsData = {
    body: UpdateSettingsRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/settings';
};

export type UpdateSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type UpdateSettingsResponses = {
    /**
     * OK
     */
    200: SettingsResponseModel;
};

export type UpdateSettingsResponse = UpdateSettingsResponses[keyof UpdateSettingsResponses];

export type TranscribeAudioData = {
    body: {
        audioFile?: IFormFile;
    };
    path?: never;
    query?: {
        profileIdOrAlias?: string;
        language?: string;
    };
    url: '/umbraco/ai/management/api/v1/speech-to-text/transcribe';
};

export type TranscribeAudioErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type TranscribeAudioError = TranscribeAudioErrors[keyof TranscribeAudioErrors];

export type TranscribeAudioResponses = {
    /**
     * OK
     */
    200: SpeechToTextResponseModel;
};

export type TranscribeAudioResponse = TranscribeAudioResponses[keyof TranscribeAudioResponses];

export type GetAllTestFeaturesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/test-features';
};

export type GetAllTestFeaturesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllTestFeaturesResponses = {
    /**
     * OK
     */
    200: Array<TestFeatureInfoModel>;
};

export type GetAllTestFeaturesResponse = GetAllTestFeaturesResponses[keyof GetAllTestFeaturesResponses];

export type GetTestFeatureByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/test-features/{id}';
};

export type GetTestFeatureByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetTestFeatureByIdError = GetTestFeatureByIdErrors[keyof GetTestFeatureByIdErrors];

export type GetTestFeatureByIdResponses = {
    /**
     * OK
     */
    200: TestFeatureResponseModel;
};

export type GetTestFeatureByIdResponse = GetTestFeatureByIdResponses[keyof GetTestFeatureByIdResponses];

export type GetAllTestGradersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/test-graders';
};

export type GetAllTestGradersErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllTestGradersResponses = {
    /**
     * OK
     */
    200: Array<TestGraderInfoModel>;
};

export type GetAllTestGradersResponse = GetAllTestGradersResponses[keyof GetAllTestGradersResponses];

export type GetTestGraderByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/test-graders/{id}';
};

export type GetTestGraderByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetTestGraderByIdError = GetTestGraderByIdErrors[keyof GetTestGraderByIdErrors];

export type GetTestGraderByIdResponses = {
    /**
     * OK
     */
    200: TestGraderResponseModel;
};

export type GetTestGraderByIdResponse = GetTestGraderByIdResponses[keyof GetTestGraderByIdResponses];

export type GetAllTestRunsData = {
    body?: never;
    path?: never;
    query?: {
        testId?: string;
        batchId?: string;
        status?: string;
        executionId?: string;
        variationId?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ai/management/api/v1/test-runs';
};

export type GetAllTestRunsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllTestRunsResponses = {
    /**
     * OK
     */
    200: PagedModelTestRunResponseModel;
};

export type GetAllTestRunsResponse = GetAllTestRunsResponses[keyof GetAllTestRunsResponses];

export type DeleteTestRunData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/test-runs/{id}';
};

export type DeleteTestRunErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteTestRunError = DeleteTestRunErrors[keyof DeleteTestRunErrors];

export type DeleteTestRunResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetTestRunByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/test-runs/{id}';
};

export type GetTestRunByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetTestRunByIdError = GetTestRunByIdErrors[keyof GetTestRunByIdErrors];

export type GetTestRunByIdResponses = {
    /**
     * OK
     */
    200: TestRunResponseModel;
};

export type GetTestRunByIdResponse = GetTestRunByIdResponses[keyof GetTestRunByIdResponses];

export type GetTestRunTranscriptData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/test-runs/{id}/transcript';
};

export type GetTestRunTranscriptErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetTestRunTranscriptError = GetTestRunTranscriptErrors[keyof GetTestRunTranscriptErrors];

export type GetTestRunTranscriptResponses = {
    /**
     * OK
     */
    200: TestTranscriptResponseModel;
};

export type GetTestRunTranscriptResponse = GetTestRunTranscriptResponses[keyof GetTestRunTranscriptResponses];

export type SetBaselineTestRunData = {
    body?: never;
    path: {
        testId: string;
        testRunId: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/test-runs/baseline/{testId}/{testRunId}';
};

export type SetBaselineTestRunErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type SetBaselineTestRunError = SetBaselineTestRunErrors[keyof SetBaselineTestRunErrors];

export type SetBaselineTestRunResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type CompareTestRunsData = {
    body: CompareRunsRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/test-runs/compare';
};

export type CompareTestRunsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type CompareTestRunsError = CompareTestRunsErrors[keyof CompareTestRunsErrors];

export type CompareTestRunsResponses = {
    /**
     * OK
     */
    200: TestRunComparisonResponseModel;
};

export type CompareTestRunsResponse = CompareTestRunsResponses[keyof CompareTestRunsResponses];

export type CompareVariationsData = {
    body: CompareVariationsRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/test-runs/compare-variations';
};

export type CompareVariationsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CompareVariationsError = CompareVariationsErrors[keyof CompareVariationsErrors];

export type CompareVariationsResponses = {
    /**
     * OK
     */
    200: TestVariationComparisonResponseModel;
};

export type CompareVariationsResponse = CompareVariationsResponses[keyof CompareVariationsResponses];

export type GetExecutionResultData = {
    body?: never;
    path: {
        executionId: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/test-runs/executions/{executionId}';
};

export type GetExecutionResultErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetExecutionResultError = GetExecutionResultErrors[keyof GetExecutionResultErrors];

export type GetExecutionResultResponses = {
    /**
     * OK
     */
    200: TestExecutionResultResponseModel;
};

export type GetExecutionResultResponse = GetExecutionResultResponses[keyof GetExecutionResultResponses];

export type GetLatestTestRunData = {
    body?: never;
    path: {
        testId: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/test-runs/latest/{testId}';
};

export type GetLatestTestRunErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetLatestTestRunError = GetLatestTestRunErrors[keyof GetLatestTestRunErrors];

export type GetLatestTestRunResponses = {
    /**
     * OK
     */
    200: TestRunResponseModel;
};

export type GetLatestTestRunResponse = GetLatestTestRunResponses[keyof GetLatestTestRunResponses];

export type GetAllTestsData = {
    body?: never;
    path?: never;
    query?: {
        filter?: string;
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ai/management/api/v1/tests';
};

export type GetAllTestsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllTestsResponses = {
    /**
     * OK
     */
    200: PagedTestItemResponseModel;
};

export type GetAllTestsResponse = GetAllTestsResponses[keyof GetAllTestsResponses];

export type CreateTestData = {
    body: CreateTestRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/tests';
};

export type CreateTestErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CreateTestError = CreateTestErrors[keyof CreateTestErrors];

export type CreateTestResponses = {
    /**
     * Created
     */
    201: unknown;
};

export type DeleteTestData = {
    body?: never;
    path: {
        idOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/tests/{idOrAlias}';
};

export type DeleteTestErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteTestError = DeleteTestErrors[keyof DeleteTestErrors];

export type DeleteTestResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type GetTestByIdOrAliasData = {
    body?: never;
    path: {
        idOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/tests/{idOrAlias}';
};

export type GetTestByIdOrAliasErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetTestByIdOrAliasError = GetTestByIdOrAliasErrors[keyof GetTestByIdOrAliasErrors];

export type GetTestByIdOrAliasResponses = {
    /**
     * OK
     */
    200: TestResponseModel;
};

export type GetTestByIdOrAliasResponse = GetTestByIdOrAliasResponses[keyof GetTestByIdOrAliasResponses];

export type UpdateTestData = {
    body: UpdateTestRequestModel;
    path: {
        idOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/tests/{idOrAlias}';
};

export type UpdateTestErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateTestError = UpdateTestErrors[keyof UpdateTestErrors];

export type UpdateTestResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type RunTestData = {
    body?: null | RunTestRequestModel;
    path: {
        idOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/tests/{idOrAlias}/run';
};

export type RunTestErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type RunTestError = RunTestErrors[keyof RunTestErrors];

export type RunTestResponses = {
    /**
     * OK
     */
    200: TestExecutionResultResponseModel;
};

export type RunTestResponse = RunTestResponses[keyof RunTestResponses];

export type GetAllEntityTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/tests/entity-types';
};

export type GetAllEntityTypesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllEntityTypesResponses = {
    /**
     * OK
     */
    200: Array<TestEntityTypeResponseModel>;
};

export type GetAllEntityTypesResponse = GetAllEntityTypesResponses[keyof GetAllEntityTypesResponses];

export type GetEntitySubTypesData = {
    body?: never;
    path: {
        entityType: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/tests/entity-types/{entityType}/sub-types';
};

export type GetEntitySubTypesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetEntitySubTypesResponses = {
    /**
     * OK
     */
    200: Array<TestEntitySubTypeResponseModel>;
};

export type GetEntitySubTypesResponse = GetEntitySubTypesResponses[keyof GetEntitySubTypesResponses];

export type RunTestBatchData = {
    body: RunTestBatchRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/tests/run-batch';
};

export type RunTestBatchErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type RunTestBatchError = RunTestBatchErrors[keyof RunTestBatchErrors];

export type RunTestBatchResponses = {
    /**
     * OK
     */
    200: TestBatchResultsResponseModel;
};

export type RunTestBatchResponse = RunTestBatchResponses[keyof RunTestBatchResponses];

export type RunTestsByTagsData = {
    body: RunTestsByTagsRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/tests/run-by-tags';
};

export type RunTestsByTagsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type RunTestsByTagsError = RunTestsByTagsErrors[keyof RunTestsByTagsErrors];

export type RunTestsByTagsResponses = {
    /**
     * OK
     */
    200: TestBatchResultsResponseModel;
};

export type RunTestsByTagsResponse = RunTestsByTagsResponses[keyof RunTestsByTagsResponses];

export type GetAllToolsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/tools';
};

export type GetAllToolsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllToolsResponses = {
    /**
     * OK
     */
    200: Array<ToolItemResponseModel>;
};

export type GetAllToolsResponse = GetAllToolsResponses[keyof GetAllToolsResponses];

export type GetAllToolScopesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/tools/scopes';
};

export type GetAllToolScopesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllToolScopesResponses = {
    /**
     * OK
     */
    200: Array<ToolScopeItemResponseModel>;
};

export type GetAllToolScopesResponse = GetAllToolScopesResponses[keyof GetAllToolScopesResponses];

export type GetVersionHistoryData = {
    body?: never;
    path: {
        entityType: string;
        entityId: string;
    };
    query?: {
        skip?: number;
        take?: number;
    };
    url: '/umbraco/ai/management/api/v1/versions/{entityType}/{entityId}';
};

export type GetVersionHistoryErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetVersionHistoryError = GetVersionHistoryErrors[keyof GetVersionHistoryErrors];

export type GetVersionHistoryResponses = {
    /**
     * OK
     */
    200: EntityVersionHistoryResponseModel;
};

export type GetVersionHistoryResponse = GetVersionHistoryResponses[keyof GetVersionHistoryResponses];

export type GetVersionData = {
    body?: never;
    path: {
        entityType: string;
        entityId: string;
        entityVersion: number;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/versions/{entityType}/{entityId}/{entityVersion}';
};

export type GetVersionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetVersionError = GetVersionErrors[keyof GetVersionErrors];

export type GetVersionResponses = {
    /**
     * OK
     */
    200: EntityVersionResponseModel;
};

export type GetVersionResponse = GetVersionResponses[keyof GetVersionResponses];

export type RollbackToVersionData = {
    body?: never;
    path: {
        entityType: string;
        entityId: string;
        entityVersion: number;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/versions/{entityType}/{entityId}/{entityVersion}/rollback';
};

export type RollbackToVersionErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type RollbackToVersionError = RollbackToVersionErrors[keyof RollbackToVersionErrors];

export type RollbackToVersionResponses = {
    /**
     * No Content
     */
    204: unknown;
};

export type CompareVersionsData = {
    body?: never;
    path: {
        entityType: string;
        entityId: string;
        fromEntityVersion: number;
        toEntityVersion: number;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/versions/{entityType}/{entityId}/{fromEntityVersion}/compare/{toEntityVersion}';
};

export type CompareVersionsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type CompareVersionsError = CompareVersionsErrors[keyof CompareVersionsErrors];

export type CompareVersionsResponses = {
    /**
     * OK
     */
    200: EntityVersionComparisonResponseModel;
};

export type CompareVersionsResponse = CompareVersionsResponses[keyof CompareVersionsResponses];

export type GetSupportedEntityTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/versions/supported-types';
};

export type GetSupportedEntityTypesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetSupportedEntityTypesResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetSupportedEntityTypesResponse = GetSupportedEntityTypesResponses[keyof GetSupportedEntityTypesResponses];
