<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>Umbraco AI</Title>
        <Description>Umbraco AI</Description>
        <PackageReadmeFile>docs\README.md</PackageReadmeFile>
        <PackageTags>umbraco ai umbraco-marketplace</PackageTags>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <IncludeSymbols>false</IncludeSymbols>
        <IncludeReferencedProjects>true</IncludeReferencedProjects>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\README.md" Pack="true" PackagePath="docs" />
    </ItemGroup>


    <PropertyGroup>
        <UseProjectReferences Condition="'$(UseProjectReferences)' == ''">true</UseProjectReferences>
    </PropertyGroup>

    <ItemGroup Condition="'$(UseProjectReferences)' == 'true'">
        <ProjectReference Include="..\Umbraco.AI.Startup\Umbraco.AI.Startup.csproj" />
        <ProjectReference Include="..\Umbraco.AI.Web.StaticAssets\Umbraco.AI.Web.StaticAssets.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(UseProjectReferences)' != 'true'">
        <PackageReference Include="Umbraco.AI.Startup" VersionOverride="[$(Version)]" />
        <PackageReference Include="Umbraco.AI.Web.StaticAssets" VersionOverride="[$(Version)]" />
    </ItemGroup>
</Project>
