using Umbraco.AI.Core.Models;

namespace Umbraco.AI.Core.Tests;

/// <summary>
/// Usage (tokens, call counts and duration) for one breakdown entry (a capability, provider, model, profile and feature combination)
/// within a test execution. The feature identifies what made the calls, for example a prompt, an agent, or a
/// guardrail judge, so graders can sum just the entries they care about.
/// </summary>
public sealed class AITestUsageEntry
{
    /// <summary>
    /// The capability the calls were made with (for example Chat or Embedding).
    /// </summary>
    public AICapability Capability { get; set; }

    /// <summary>
    /// The ID of the provider that served the calls, if known.
    /// </summary>
    public string? ProviderId { get; set; }

    /// <summary>
    /// The ID of the model that served the calls, if known.
    /// </summary>
    public string? ModelId { get; set; }

    /// <summary>
    /// The ID of the profile the calls resolved to, if any.
    /// </summary>
    public Guid? ProfileId { get; set; }

    /// <summary>
    /// The alias of the profile the calls resolved to, if any.
    /// </summary>
    public string? ProfileAlias { get; set; }

    /// <summary>
    /// The type of feature that made the calls (for example "prompt", "agent" or "inline-chat"), if any.
    /// </summary>
    public string? FeatureType { get; set; }

    /// <summary>
    /// The ID of the feature (for example the prompt or agent) that made the calls, if any.
    /// </summary>
    public Guid? FeatureId { get; set; }

    /// <summary>
    /// The alias of the feature that made the calls, if any (for example "guardrail-llm-evaluator").
    /// </summary>
    public string? FeatureAlias { get; set; }

    /// <summary>
    /// Number of input tokens consumed by these calls.
    /// </summary>
    public int InputTokens { get; set; }

    /// <summary>
    /// Number of output tokens generated by these calls.
    /// </summary>
    public int OutputTokens { get; set; }

    /// <summary>
    /// Total tokens (input + output) for these calls. This is a lower bound when
    /// <see cref="UnreportedCallCount"/> is greater than zero.
    /// </summary>
    public int TotalTokens { get; set; }

    /// <summary>
    /// Number of tracked calls made with this entry's combination, including calls that reported no usage.
    /// </summary>
    public int CallCount { get; set; }

    /// <summary>
    /// Number of calls in this entry that returned no usage details.
    /// </summary>
    public int UnreportedCallCount { get; set; }

    /// <summary>
    /// Sum of the durations, in milliseconds, of the calls in this entry. Overlapping calls are summed,
    /// so this is AI time, not wall-clock time.
    /// </summary>
    public long DurationMs { get; set; }

    /// <summary>
    /// Number of calls in this entry that failed. Failed calls are included in <see cref="CallCount"/>.
    /// </summary>
    public int FailedCallCount { get; set; }
}
