// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://127.0.0.1:44355' | (string & {});
};

export type AgentItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    description?: string | null;
    profileId?: string | null;
    contextIds: Array<string>;
    scopeIds: Array<string>;
    isActive: boolean;
    dateCreated: string;
    dateModified: string;
};

export type AgentResponseModel = {
    id: string;
    alias: string;
    name: string;
    description?: string | null;
    profileId?: string | null;
    contextIds: Array<string>;
    scopeIds: Array<string>;
    instructions?: string | null;
    isActive: boolean;
    dateCreated: string;
    dateModified: string;
    version: number;
};

export type AgentScopeItemResponseModel = {
    id: string;
    icon: string;
};

export type AguiContextItemModel = {
    description: string;
    value?: string | null;
};

export type AguiFunctionCallModel = {
    name: string;
    arguments: string;
};

export type AguiMessageModel = {
    id?: string | null;
    role: AguiMessageRoleModel;
    content?: string | null;
    name?: string | null;
    toolCalls?: Array<AguiToolCallModel> | null;
    toolCallId?: string | null;
};

export type AguiMessageRoleModel = 'User' | 'Assistant' | 'System' | 'Tool' | 'Developer' | 'Activity';

export type AguiResumeInfoModel = {
    interruptId: string;
    payload?: unknown;
};

export type AguiRunRequestModel = {
    threadId: string;
    runId: string;
    messages: Array<AguiMessageModel>;
    tools?: Array<AguiToolModel> | null;
    state?: unknown;
    context?: Array<AguiContextItemModel> | null;
    resume?: AguiResumeInfoModel | null;
    forwardedProps?: unknown;
};

export type AguiToolCallModel = {
    id: string;
    type: string;
    function: AguiFunctionCallModel;
};

export type AguiToolModel = {
    name: string;
    description: string;
    parameters: AguiToolParametersModel;
};

export type AguiToolParametersModel = {
    type: string;
    properties: unknown;
    required?: Array<string> | null;
};

export type CreateAgentRequestModel = {
    alias: string;
    name: string;
    description?: string | null;
    profileId?: string | null;
    contextIds?: Array<string> | null;
    scopeIds?: Array<string> | null;
    instructions?: string | null;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type PagedAgentItemResponseModel = {
    total: number;
    items: Array<AgentItemResponseModel>;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type UpdateAgentRequestModel = {
    alias: string;
    name: string;
    description?: string | null;
    profileId?: string | null;
    contextIds?: Array<string> | null;
    scopeIds?: Array<string> | null;
    instructions?: string | null;
    isActive: boolean;
};

export type ValidationProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    errors: {
        [key: string]: Array<string>;
    };
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | {
        [key: string]: Array<string>;
    } | undefined;
};

export type GetAllAgentsData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
        filter?: string;
        profileId?: string;
        scopeId?: string;
        isActive?: boolean;
    };
    url: '/umbraco/ai/management/api/v1/agents';
};

export type GetAllAgentsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllAgentsResponses = {
    /**
     * OK
     */
    200: PagedAgentItemResponseModel;
};

export type GetAllAgentsResponse = GetAllAgentsResponses[keyof GetAllAgentsResponses];

export type CreateAgentData = {
    body?: CreateAgentRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/agents';
};

export type CreateAgentErrors = {
    /**
     * Bad Request
     */
    400: ValidationProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type CreateAgentError = CreateAgentErrors[keyof CreateAgentErrors];

export type CreateAgentResponses = {
    /**
     * Created
     */
    201: AgentResponseModel;
};

export type CreateAgentResponse = CreateAgentResponses[keyof CreateAgentResponses];

export type DeleteAgentData = {
    body?: never;
    path: {
        agentIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/agents/{agentIdOrAlias}';
};

export type DeleteAgentErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteAgentError = DeleteAgentErrors[keyof DeleteAgentErrors];

export type DeleteAgentResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteAgentResponse = DeleteAgentResponses[keyof DeleteAgentResponses];

export type GetAgentByIdOrAliasData = {
    body?: never;
    path: {
        agentIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/agents/{agentIdOrAlias}';
};

export type GetAgentByIdOrAliasErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetAgentByIdOrAliasError = GetAgentByIdOrAliasErrors[keyof GetAgentByIdOrAliasErrors];

export type GetAgentByIdOrAliasResponses = {
    /**
     * OK
     */
    200: AgentResponseModel;
};

export type GetAgentByIdOrAliasResponse = GetAgentByIdOrAliasResponses[keyof GetAgentByIdOrAliasResponses];

export type UpdateAgentData = {
    body?: UpdateAgentRequestModel;
    path: {
        agentIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/agents/{agentIdOrAlias}';
};

export type UpdateAgentErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateAgentError = UpdateAgentErrors[keyof UpdateAgentErrors];

export type UpdateAgentResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type RunAgentData = {
    body?: AguiRunRequestModel;
    path: {
        agentIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/agents/{agentIdOrAlias}/run';
};

export type RunAgentErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type RunAgentError = RunAgentErrors[keyof RunAgentErrors];

export type RunAgentResponses = {
    /**
     * Server-Sent Events stream
     */
    200: string;
};

export type RunAgentResponse = RunAgentResponses[keyof RunAgentResponses];

export type GetAgentScopesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/agents/scopes';
};

export type GetAgentScopesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAgentScopesResponses = {
    /**
     * OK
     */
    200: Array<AgentScopeItemResponseModel>;
};

export type GetAgentScopesResponse = GetAgentScopesResponses[keyof GetAgentScopesResponses];
