// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AGUIContextItemModel = {
    description: string;
    value?: string | null;
};

export type AGUIFunctionCallModel = {
    name: string;
    arguments: string;
};

export type AGUIMessageModel = {
    id?: string | null;
    role: AGUIMessageRoleModel;
    content?: string | null;
    name?: string | null;
    toolCalls?: Array<AGUIToolCallModel> | null;
    toolCallId?: string | null;
};

export type AGUIMessageRoleModel = 'User' | 'Assistant' | 'System' | 'Tool' | 'Developer' | 'Activity';

export type AGUIResumeInfoModel = {
    interruptId: string;
    payload?: unknown;
};

export type AGUIRunRequestModel = {
    threadId: string;
    runId: string;
    messages: Array<AGUIMessageModel>;
    tools?: Array<AGUIToolModel> | null;
    state?: unknown;
    context?: Array<AGUIContextItemModel> | null;
    resume?: AGUIResumeInfoModel | null;
    forwardedProps?: unknown;
};

export type AGUIToolCallModel = {
    id: string;
    type: string;
    function: AGUIFunctionCallModel;
};

export type AGUIToolModel = {
    name: string;
    description: string;
    parameters: AGUIToolParametersModel;
};

export type AGUIToolParametersModel = {
    type: string;
    properties: unknown;
    required?: Array<string> | null;
};

export type AiAgentScopeModel = {
    allowRules: Array<AiAgentScopeRuleModel>;
    denyRules: Array<AiAgentScopeRuleModel>;
};

export type AiAgentScopeRuleModel = {
    sections?: Array<string> | null;
    entityTypes?: Array<string> | null;
};

export type AiAgentUserGroupPermissionsModel = {
    allowedToolIds: Array<string>;
    allowedToolScopeIds: Array<string>;
    deniedToolIds: Array<string>;
    deniedToolScopeIds: Array<string>;
};

export type AgentConfigModel = {
    [key: string]: never;
};

export type AgentItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    description?: string | null;
    agentType: string;
    profileId?: string | null;
    surfaceIds: Array<string>;
    scope?: AiAgentScopeModel | null;
    isActive: boolean;
    dateCreated: string;
    dateModified: string;
};

export type AgentResponseModel = {
    id: string;
    alias: string;
    name: string;
    description?: string | null;
    agentType: string;
    profileId?: string | null;
    guardrailIds: Array<string>;
    surfaceIds: Array<string>;
    scope?: AiAgentScopeModel | null;
    config?: StandardAgentConfigModel | OrchestratedAgentConfigModel | null;
    isActive: boolean;
    dateCreated: string;
    dateModified: string;
    version: number;
};

export type AgentSurfaceItemResponseModel = {
    id: string;
    icon: string;
    supportedScopeDimensions: Array<string>;
};

export type AgentWorkflowItemResponseModel = {
    id: string;
    name: string;
    description?: string | null;
    settingsSchema?: EditableModelSchemaModel | null;
};

export type CreateAgentRequestModel = {
    alias: string;
    name: string;
    description?: string | null;
    agentType: string;
    profileId?: string | null;
    guardrailIds?: Array<string> | null;
    surfaceIds?: Array<string> | null;
    scope?: AiAgentScopeModel | null;
    config?: StandardAgentConfigModel | OrchestratedAgentConfigModel | null;
};

export type EditableModelFieldModel = {
    key: string;
    label: string;
    description?: string | null;
    editorUiAlias?: string | null;
    editorConfig?: unknown;
    defaultValue?: unknown;
    sortOrder: number;
    isRequired: boolean;
    group?: string | null;
};

export type EditableModelSchemaModel = {
    type?: string | null;
    fields: Array<EditableModelFieldModel>;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type OrchestratedAgentConfigModel = AgentConfigModel & {
    $type: string;
    workflowId?: string | null;
    settings?: unknown;
};

export type PagedAgentItemResponseModel = {
    total: number;
    items: Array<AgentItemResponseModel>;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type StandardAgentConfigModel = AgentConfigModel & {
    $type: string;
    contextIds?: Array<string> | null;
    instructions?: string | null;
    allowedToolIds?: Array<string> | null;
    allowedToolScopeIds?: Array<string> | null;
    userGroupPermissions?: {
        [key: string]: AiAgentUserGroupPermissionsModel;
    } | null;
};

export type UpdateAgentRequestModel = {
    alias: string;
    name: string;
    description?: string | null;
    profileId?: string | null;
    guardrailIds?: Array<string> | null;
    surfaceIds?: Array<string> | null;
    scope?: AiAgentScopeModel | null;
    config?: StandardAgentConfigModel | OrchestratedAgentConfigModel | null;
    isActive: boolean;
};

export type ValidationProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    errors: {
        [key: string]: Array<string>;
    };
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | {
        [key: string]: Array<string>;
    } | undefined;
};

export type GetAllAgentsData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
        filter?: string;
        profileId?: string;
        scopeId?: string;
        isActive?: boolean;
        agentType?: string;
    };
    url: '/umbraco/ai/management/api/v1/agents';
};

export type GetAllAgentsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllAgentsResponses = {
    /**
     * OK
     */
    200: PagedAgentItemResponseModel;
};

export type GetAllAgentsResponse = GetAllAgentsResponses[keyof GetAllAgentsResponses];

export type CreateAgentData = {
    body?: CreateAgentRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/agents';
};

export type CreateAgentErrors = {
    /**
     * Bad Request
     */
    400: ValidationProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type CreateAgentError = CreateAgentErrors[keyof CreateAgentErrors];

export type CreateAgentResponses = {
    /**
     * Created
     */
    201: AgentResponseModel;
};

export type CreateAgentResponse = CreateAgentResponses[keyof CreateAgentResponses];

export type DeleteAgentData = {
    body?: never;
    path: {
        agentIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/agents/{agentIdOrAlias}';
};

export type DeleteAgentErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteAgentError = DeleteAgentErrors[keyof DeleteAgentErrors];

export type DeleteAgentResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteAgentResponse = DeleteAgentResponses[keyof DeleteAgentResponses];

export type GetAgentByIdOrAliasData = {
    body?: never;
    path: {
        agentIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/agents/{agentIdOrAlias}';
};

export type GetAgentByIdOrAliasErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetAgentByIdOrAliasError = GetAgentByIdOrAliasErrors[keyof GetAgentByIdOrAliasErrors];

export type GetAgentByIdOrAliasResponses = {
    /**
     * OK
     */
    200: AgentResponseModel;
};

export type GetAgentByIdOrAliasResponse = GetAgentByIdOrAliasResponses[keyof GetAgentByIdOrAliasResponses];

export type UpdateAgentData = {
    body?: UpdateAgentRequestModel;
    path: {
        agentIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/agents/{agentIdOrAlias}';
};

export type UpdateAgentErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateAgentError = UpdateAgentErrors[keyof UpdateAgentErrors];

export type UpdateAgentResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type StreamAgentAGUIData = {
    body?: AGUIRunRequestModel;
    path: {
        agentIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/agents/{agentIdOrAlias}/stream-agui';
};

export type StreamAgentAGUIErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type StreamAgentAGUIError = StreamAgentAGUIErrors[keyof StreamAgentAGUIErrors];

export type StreamAgentAGUIResponses = {
    /**
     * Server-Sent Events stream
     */
    200: string;
};

export type StreamAgentAGUIResponse = StreamAgentAGUIResponses[keyof StreamAgentAGUIResponses];

export type AgentAliasExistsData = {
    body?: never;
    path: {
        alias: string;
    };
    query?: {
        excludeId?: string;
    };
    url: '/umbraco/ai/management/api/v1/agents/{alias}/exists';
};

export type AgentAliasExistsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type AgentAliasExistsResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type AgentAliasExistsResponse = AgentAliasExistsResponses[keyof AgentAliasExistsResponses];

export type GetAgentSurfacesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/agents/surfaces';
};

export type GetAgentSurfacesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAgentSurfacesResponses = {
    /**
     * OK
     */
    200: Array<AgentSurfaceItemResponseModel>;
};

export type GetAgentSurfacesResponse = GetAgentSurfacesResponses[keyof GetAgentSurfacesResponses];

export type GetAgentWorkflowsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/agents/workflows';
};

export type GetAgentWorkflowsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAgentWorkflowsResponses = {
    /**
     * OK
     */
    200: Array<AgentWorkflowItemResponseModel>;
};

export type GetAgentWorkflowsResponse = GetAgentWorkflowsResponses[keyof GetAgentWorkflowsResponses];
