// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44363' | (string & {});
};

export type AgentItemResponseModel = {
    id: string;
    alias: string;
    name: string;
    description?: string | null;
    profileId?: string | null;
    isActive: boolean;
};

export type AgentResponseModel = {
    id: string;
    alias: string;
    name: string;
    description?: string | null;
    content: string;
    profileId?: string | null;
    tags: Array<string>;
    isActive: boolean;
    scope?: ScopeModel | null;
    dateCreated: string;
    dateModified: string;
};

export type CreateAgentRequestModel = {
    alias: string;
    name: string;
    content: string;
    description?: string | null;
    profileId?: string | null;
    tags?: Array<string> | null;
    scope?: ScopeModel | null;
};

export type EventMessageTypeModel = 'Default' | 'Info' | 'Error' | 'Success' | 'Warning';

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type PagedAgentItemResponseModel = {
    total: number;
    items: Array<AgentItemResponseModel>;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | undefined;
};

export type ScopeModel = {
    allowRules: Array<ScopeRuleModel>;
    denyRules: Array<ScopeRuleModel>;
};

export type ScopeRuleModel = {
    propertyEditorUiAliases?: Array<string> | null;
    propertyAliases?: Array<string> | null;
    contentTypeAliases?: Array<string> | null;
};

export type UpdateAgentRequestModel = {
    alias: string;
    name: string;
    content: string;
    description?: string | null;
    profileId?: string | null;
    tags?: Array<string> | null;
    isActive: boolean;
    scope?: ScopeModel | null;
};

export type ValidationProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    errors: {
        [key: string]: Array<string>;
    };
    [key: string]: unknown | string | null | string | null | number | null | string | null | string | null | {
        [key: string]: Array<string>;
    } | undefined;
};

export type GetAllAgentsData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        take?: number;
        filter?: string;
        profileId?: string;
    };
    url: '/umbraco/ai/management/api/v1/agents';
};

export type GetAllAgentsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAllAgentsResponses = {
    /**
     * OK
     */
    200: PagedAgentItemResponseModel;
};

export type GetAllAgentsResponse = GetAllAgentsResponses[keyof GetAllAgentsResponses];

export type CreateAgentData = {
    body?: CreateAgentRequestModel;
    path?: never;
    query?: never;
    url: '/umbraco/ai/management/api/v1/agents';
};

export type CreateAgentErrors = {
    /**
     * Bad Request
     */
    400: ValidationProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type CreateAgentError = CreateAgentErrors[keyof CreateAgentErrors];

export type CreateAgentResponses = {
    /**
     * Created
     */
    201: AgentResponseModel;
};

export type CreateAgentResponse = CreateAgentResponses[keyof CreateAgentResponses];

export type DeleteAgentData = {
    body?: never;
    path: {
        agentIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/agents/{agentIdOrAlias}';
};

export type DeleteAgentErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteAgentError = DeleteAgentErrors[keyof DeleteAgentErrors];

export type DeleteAgentResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteAgentResponse = DeleteAgentResponses[keyof DeleteAgentResponses];

export type GetAgentByIdOrAliasData = {
    body?: never;
    path: {
        agentIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/agents/{agentIdOrAlias}';
};

export type GetAgentByIdOrAliasErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetAgentByIdOrAliasError = GetAgentByIdOrAliasErrors[keyof GetAgentByIdOrAliasErrors];

export type GetAgentByIdOrAliasResponses = {
    /**
     * OK
     */
    200: AgentResponseModel;
};

export type GetAgentByIdOrAliasResponse = GetAgentByIdOrAliasResponses[keyof GetAgentByIdOrAliasResponses];

export type UpdateAgentData = {
    body?: UpdateAgentRequestModel;
    path: {
        agentIdOrAlias: string;
    };
    query?: never;
    url: '/umbraco/ai/management/api/v1/agents/{agentIdOrAlias}';
};

export type UpdateAgentErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type UpdateAgentError = UpdateAgentErrors[keyof UpdateAgentErrors];

export type UpdateAgentResponses = {
    /**
     * OK
     */
    200: unknown;
};
